// ============================================
// KSLT Admin — Constants, Labels, Enums
// ============================================

(function() {
    'use strict';

    var isEn = window.location.pathname.indexOf('-en') !== -1;

    // ---- Labels ----
    var L = isEn ? {
        dashboard: 'Dashboard',
        users: 'Users',
        tournaments: 'Tournaments',
        players: 'Players',
        content: 'News',
        memberships: 'Memberships',
        soon: 'Soon',
        dashboardTitle: 'Dashboard',
        totalUsers: 'Total Users',
        activeMemberships: 'Active Memberships',
        upcomingTournaments: 'Upcoming Tournaments',
        rankedPlayers: 'Ranked Players',
        recentRegistrations: 'Recent Registrations',
        thUser: 'User',
        thEmail: 'Email',
        thRole: 'Role',
        thDate: 'Registered',
        roleAdmin: 'Admin',
        roleManager: 'Manager',
        rolePlayer: 'Player',
        roleUser: 'User',
        comingSoonTitle: 'Coming Soon',
        comingSoonText: 'This section is under development',
        noData: '—',
        iconUsers: '👥',
        iconMemberships: '💳',
        iconTournaments: '🏆',
        iconPlayers: '📊',
        // Dashboard cards
        iconOverdue: '⚠️',
        iconApproaching: '⏰',
        iconNews: '📰',
        statMembersDetail: 'members / users',
        statOverdueDetail: 'expired memberships',
        statApproachingDetail: 'expiring within 10 days',
        statTournamentsDetail: 'past / upcoming',
        statNewsDetail: 'articles published',
        // Dashboard activity tables
        actApproaching: 'Approaching Payment',
        actOverdue: 'Overdue Payments',
        actRecentRegistrations: 'Recent Registrations',
        actRecentTournaments: 'Recent Tournaments',
        actRecentNews: 'Recent News',
        dashChartTitle: 'User Growth (12 months)',
        dashChartRegistered: 'Registered',
        dashChartDeleted: 'Deleted',
        dashChartNet: 'Net',
        viewAll: 'View all',
        thName: 'Name',
        thExpires: 'Expires',
        thDaysLeft: 'Days Left',
        thOverdueDays: 'Overdue',
        thTournament: 'Tournament',
        thDateStart: 'Date',
        thArticle: 'Article',
        thStatus: 'Status',
        iconPending: '📋',
        iconCourts: '🏟️',
        iconCoaches: '🎓',
        iconManagers: '👔',
        statPendingDetail: 'pending registrations',
        statCourtsDetail: 'courts total',
        statCoachesDetail: 'coaches total',
        statManagersDetail: 'managers',
        actPendingRegs: 'Pending Registrations',
        thPlayer: 'Player',
        thCategory: 'Category',
        noPendingRegs: 'No pending registrations',
        noApproaching: 'No expiring memberships',
        noOverdue: 'No overdue payments',
        noRecentUsers: 'No recent registrations',
        noRecentTournaments: 'No recent tournaments',
        noRecentNews: 'No recent news',
        // News
        addNews: 'Add Article',
        editNews: 'Edit Article',
        newsList: 'All Articles',
        newsTitle: 'Title',
        newsSlug: 'Slug',
        newsExcerpt: 'Excerpt',
        newsContent: 'Content',
        newsImage: 'Cover Image',
        newsCategory: 'Category',
        newsAuthor: 'Author',
        newsPublishedAt: 'Publish Date',
        newsDraft: 'Draft',
        newsPublished: 'Published',
        newsSearch: 'Search by title...',
        newsAll: 'All',
        save: 'Save',
        saving: 'Saving...',
        saved: 'Saved!',
        delete: 'Delete',
        deleteSelected: 'Delete Selected',
        deleteSelectedConfirm: 'Delete selected items?',
        deleteConfirm: 'Delete this article?',
        deleteConfirmText: 'This action cannot be undone.',
        cancel: 'Cancel',
        back: 'Back to List',
        uploadImage: 'Click to upload or drag image',
        uploadHint: 'JPG or PNG, max 2MB',
        orPasteUrl: 'Or paste image URL',
        applyUrl: 'Apply',
        publish: 'Publish',
        update: 'Update',
        newsGallery: 'Gallery',
        contentPreview: 'Preview',
        insertPhoto: '+ Photo',
        pollSection: 'Poll',
        pollQuestion: 'Question',
        pollOption: 'Option',
        pollAdd: '+ Add option',
        pollEnable: 'Add poll',
        pollRemove: 'Remove poll',
        thReactions: 'Reactions',
        thVotes: 'Votes',
        engagement: 'Engagement',
        totalVotes: 'Total votes',
        newsStatPublished: 'Published',
        newsStatDrafts: 'Drafts',
        newsStatPopular: 'Most Popular',
        newsStatLastDate: 'Last',
        newsStatNoArticles: 'No articles yet',
        catResults: 'Report',
        catInterview: 'Interview',
        catAnnouncement: 'Announcement',
        catWorld: 'World Tennis',
        selectCategory: '— Select —',
        slugHint: 'Auto-generated from title. Used in URL.',
        translateBtn: 'Translate from RU',
        translating: 'Translating...',
        translateError: 'Translation error',
        fillRuFirst: 'Fill in RU field first',
        fillAnyLang: 'Fill in any language',
        textCopied: 'Text copied',
        metaReadTime: 'min read',
        translateFromAny: 'Translate',
        noArticles: 'No articles yet',
        noArticlesText: 'Click "Add Article" to create your first article',
        thTitle: 'Title',
        thCategory: 'Category',
        thStatus: 'Status',
        thPublished: 'Date',
        thPubDate: 'Pub. Date',
        thViews: 'Views',
        thExecutor: 'Executor',
        newsExecutor: 'Executor',
        draftSaved: 'Draft saved',
        unsavedChanges: 'Unsaved changes',
        unsavedChangesText: 'You have unsaved changes. Leave without saving?',
        unsavedLeaveBtn: 'Leave',
        // Tournaments
        addTournament: 'Add Tournament',
        editTournament: 'Edit Tournament',
        trnTitle: 'Title',
        trnDescription: 'Description',
        trnLocation: 'Location',
        trnCategory: 'Category',
        trnStatus: 'Status',
        trnDateStart: 'Start Date',
        trnDateEnd: 'End Date',
        trnDateEndShort: 'End Date',
        trnMaxParticipants: 'Max Participants',
        trnMaxParticipantsShort: 'Max Part.',
        trnPrizeFund: 'Prize Fund',
        trnImage: 'Cover Image',
        noTournaments: 'No tournaments yet',
        noTournamentsText: 'Click "Add Tournament" to create your first tournament',
        trnDeleteConfirm: 'Delete this tournament?',
        trnDraft: 'Draft',
        trnCancelTournament: 'Cancel Tournament',
        trnCancelConfirm: 'Cancel this tournament? It will be marked as cancelled.',
        trnNotify: 'Notify via Telegram',
        trnNotifySent: 'Sent',
        trnNotifyConfirm: 'Send tournament announcement to Telegram group?',
        trnNotifyBtn: 'Send',
        statusUpcoming: 'Upcoming',
        statusRegOpen: 'Registration Open',
        statusRegClosed: 'Registration Closed',
        statusOngoing: 'Ongoing',
        statusCompleted: 'Completed',
        statusCancelled: 'Cancelled',
        selectStatus: '— Select —',
        selectCategoryTrn: '— Select —',
        trnFormat: 'Format',
        formatSingles: 'Singles',
        formatDoubles: 'Doubles',
        formatMixedDoubles: 'Mixed Doubles',
        selectFormat: '— Select —',
        genderMen: 'Men',
        genderWomen: 'Women',
        trnDrawSize: 'Draw Size',
        trnBracketType: 'Bracket Type',
        trnCourtCount: 'Courts',
        trnMatchDuration: 'Match Duration (min)',
        trnStartTime: 'Start Time',
        trnBuffer: 'Buffer (min)',
        trnRegStart: 'Registration Start',
        trnRegEnd: 'Registration End',
        trnVenue: 'Venue',
        trnVenueSearch: 'Search court by name...',
        trnVenueClear: 'Clear',
        trnVenueAddress: 'Address',
        trnVenuePhone: 'Phone',
        trnVenueMap: 'Map',
        bracketSE: 'Single Elimination',
        bracketFIC: 'Full Consolation (All Places)',
        bracketRR: 'Group Stage',
        trnGroupCount: 'Number of Groups',
        trnQualifiers: 'Qualifiers per Group',
        generatePlayoff: 'Generate Playoff',
        generatePlayoffConfirm: 'Generate playoff bracket from group winners?',
        playoffTitle: 'Playoff',
        groupStageTitle: 'Group Stage',
        groupLabel: 'Group',
        groupPoints: 'Pts',
        groupPlace: 'Place',
        groupWins: 'W',
        groupLosses: 'L',
        selectDrawSize: '— Select —',
        selectBracketType: '— Select —',
        trnStatTotal: 'Total Tournaments',
        trnStatUpcoming: 'Upcoming',
        trnStatCompleted: 'Completed',
        trnStatMenSingles: "Men's Singles",
        trnStatWomenSingles: "Women's Singles",
        trnStatMenDoubles: "Men's Doubles",
        trnStatWomenDoubles: "Women's Doubles",
        trnStatFriendly: 'Friendly',
        trnSearch: 'Search by title...',
        trnAllCategories: 'All Categories',
        trnAllStatuses: 'All Statuses',
        // Bracket management
        bracketTab: 'Bracket',
        registrationsTab: 'Registrations',
        scheduleTab: 'Schedule',
        resultsTab: 'Results',
        trnTabEdit: 'Edit',
        trnTabRegs: 'Registrations',
        trnTabBracket: 'Bracket',
        trnTabSchedule: 'Schedule',
        trnTabPoints: 'Results',
        schedTime: 'Time',
        schedCourt: 'Court',
        schedMatch: 'Match',
        schedRound: 'Round',
        schedSave: 'Save Schedule',
        schedSaved: 'Schedule saved',
        schedCourtTitle: 'Court',
        resPlace: 'Place',
        resPlayer: 'Player',
        resRound: 'Round Reached',
        resPoints: 'Points',
        resTotalPlayers: 'Total players',
        generateDraw: 'Generate Draw',
        generateDrawConfirm: 'Generate draw? This will create the bracket and close registration.',
        drawGenerated: 'Draw generated successfully',
        noRegistrations: 'No registrations yet',
        regStatus: 'Status',
        regApprove: 'Approve',
        regReject: 'Reject',
        regApproved: 'Approved',
        regRejected: 'Rejected',
        regPending: 'Pending',
        regWithdrawn: 'Withdrawn',
        regCount: 'registered',
        regMainDraw: 'Main Draw',
        regWaitlist: 'Waitlist',
        regRemoveSelected: 'Remove Selected',
        regRemoveConfirm: 'Remove selected participants?',
        regNoWaitlist: 'No waitlisted players',
        regWaitlistInfo: 'Awaiting admin approval',
        enterScore: 'Enter Score',
        saveScore: 'Save Score',
        addSet: '+ Add Set',
        removeSet: '- Remove Set',
        matchScore: 'Score',
        matchWinner: 'Winner',
        matchCompleted: 'completed',
        matchUpcoming: 'upcoming',
        matchLive: 'live',
        finalizeTournament: 'Finalize Tournament',
        finalizeConfirm: 'Finalize tournament? This will calculate points for all players.',
        tournamentFinalized: 'Tournament finalized. Points calculated.',
        regenerateDraw: 'Regenerate Draw',
        regenerateConfirm: 'Regenerate draw? All current matches will be deleted and a new draw created from current registrations.',
        seedLabel: 'Seed',
        byeLabel: 'BYE',
        vsLabel: 'vs',
        roundR1: 'Round 1',
        roundQF: 'Quarterfinals',
        roundSF: 'Semifinals',
        roundF: 'Final',
        round3rd: '3rd Place',
        roundR16: 'Round of 16',
        // Players
        addPlayer: 'Add Player',
        editPlayer: 'Edit Player',
        plrName: 'Name',
        plrCountry: 'Country',
        plrCategory: 'Category',
        plrPoints: 'Points',
        plrWins: 'Wins',
        plrLosses: 'Losses',
        plrRankChange: 'Rank Change',
        plrForm: 'Recent Form',
        plrBadges: 'Achievements',
        badgeEarned: 'Earned',
        badgeLocked: 'Locked',
        badgeHowTo: 'How to earn',
        badgeManualAward: 'Award badge',
        badgeRemove: 'Remove',
        badgeNewToast: 'New badge',
        badgeCheckBtn: 'Check badges',
        badgeNoEarned: 'No badges yet',
        plrBio: 'Biography',
        plrPhone: 'Phone',
        plrEmail: 'Email',
        plrPhoto: 'Photo',
        plrShowPhone: 'Show phone publicly',
        noPlayers: 'No players yet',
        noPlayersText: 'Click "Add Player" to add your first player',
        plrDeleteConfirm: 'Delete this player?',
        plrSearch: 'Search by name...',
        plrAllCategories: 'All Categories',
        badgeChampion: 'Champion',
        badgeTop1: 'Top 1',
        badgeStreak: 'Win Streak',
        badgeNewbie: 'Newcomer',
        badgeBreakthrough: 'Breakthrough',
        thPoints: 'Points',
        thWL: 'W/L',
        thChange: 'Change',
        // Courts
        courts: 'Courts',
        addCourt: 'Add Court',
        editCourt: 'Edit Court',
        crtName: 'Name',
        crtType: 'Type',
        crtSurface: 'Surface',
        crtCourtsCount: 'Qty',
        crtPrice: 'Price<br><span style="font-size:0.65rem;font-weight:400;color:var(--text-dim);">(som/hr)</span>',
        crtMobile: 'Mobile',
        crtLandline: 'Landline',
        crtAddPhone: '+ Add phone',
        crtEmail: 'Email',
        crtDescription: 'Description',
        crtAmenities: 'Amenities',
        crtPartner: 'Partner',
        crtPromoted: 'Promoted',
        crtPhoto: 'Main Photo',
        crtGallery: 'Gallery',
        crtGoogleMaps: 'Google Maps',
        crtTwoGis: '2GIS',
        crtStreet: 'Street',
        crtBuilding: 'Number',
        crtDistrict: 'District / Landmark',
        crtCity: 'City',
        crtPostalCode: 'Postal Code',
        crtSlogan: 'Additional Info',
        crtAdd: '+ Add',
        noCourts: 'No courts yet',
        noCourtsText: 'Click "Add Court" to add your first court',
        crtDeleteConfirm: 'Delete this court?',
        crtSearch: 'Search by name...',
        crtAllTypes: 'All Types',
        crtStatOutdoor: 'Outdoor',
        crtStatIndoor: 'Indoor',
        crtStatTotal: 'Total',
        crtAllSurfaces: 'All Surfaces',
        crtOther: 'Other',
        crtCustomAmenity: 'Custom amenity',
        crtAddCustom: '+ Add custom',
        crtAddByUrl: '+ By URL',
        translateAllBtn: 'Translate to empty',
        allFieldsFilled: 'All fields are already filled',
        // Coaches
        coaches: 'Coaches',
        addCoach: 'Add Coach',
        editCoach: 'Edit Coach',
        cchLastName: 'Last Name',
        cchFirstName: 'First Name',
        cchPatronymic: 'Patronymic',
        cchPosition: 'Position',
        cchTags: 'Tags',
        cchExperience: 'Experience (years)',
        cchPrice: 'Price (som/hr)',
        cchShortDesc: 'Short Description',
        cchBio: 'Biography',
        cchAchievements: 'Achievements',
        cchAchievementAdd: '+ Add achievement',
        cchCourt: 'Court / Club',
        cchPhone: 'Phone (internal)',
        cchTelegram: 'Telegram',
        cchWhatsapp: 'WhatsApp',
        cchPhoto: 'Photo',
        noCoaches: 'No coaches yet',
        noCoachesText: 'Click "Add Coach" to add your first coach',
        cchDeleteConfirm: 'Delete this coach?',
        cchSearch: 'Search by name...',
        cchAllTags: 'All Tags',
        cchPromoted: 'Promoted',
        cchStatTotal: 'Total Coaches',
        cchStatPromoted: 'Promoted',
        cchStatNew: 'New This Month',
        cchViewTitle: 'Coach Overview',
        cchViewInfo: 'Information',
        cchViewPayments: 'Payments & Services',
        cchViewNoPayments: 'No payments for this coach',
        cchViewEdit: 'Edit',
        cchPromotedBadge: 'Promoted',
        cchPromotedHint: 'Managed via Payments section',
        // Ratings
        ratings: 'Ratings',
        ratSubRankings: 'Rankings',
        ratSubResults: 'Results',
        ratSubRules: 'Points Rules',
        ratSubPromotions: 'Promotions',
        ratSelectCategory: 'Select category',
        ratAllCategories: 'All Categories',
        ratRank: '#',
        ratPlayer: 'Player',
        ratPoints: 'Points',
        ratWL: 'W/L',
        ratForm: 'Form',
        ratNoPlayers: 'No players in this category',
        ratSelectTournament: 'Select tournament',
        ratCompletedOnly: 'Completed tournaments only',
        ratRound: 'Round',
        ratPointsEarned: 'Points',
        ratAddResult: '+ Add Result',
        ratSaveResults: 'Save Results',
        ratNoResults: 'No results entered yet',
        ratLevel: 'Tournament Level',
        ratW: 'Winner',
        ratF: 'Finalist',
        rat3RD: '3rd Place',
        rat4TH: '4th Place',
        ratSF: 'Semifinal',
        ratQF: 'Quarterfinal',
        ratR16: 'Round of 16',
        ratR32: 'Round of 32',
        ratG3: '3rd in Group',
        ratG4: '4th in Group',
        ratG5: '5th in Group',
        ratG6: '6th in Group',
        ratSaveRules: 'Save Rules',
        ratAddLevel: '+ Add Level',
        ratLevelName: 'Level Name',
        ratLevelNameEn: 'Level Name (EN)',
        ratDeleteLevel: 'Delete Level',
        ratDeleteLevelConfirm: 'Delete this level and all its rules?',
        ratLevelAdded: 'Level added',
        ratLevelDeleted: 'Level deleted',
        ratRulesSaved: 'Points rules saved',
        ratResultsSaved: 'Results saved, points recalculated',
        ratEligible: 'Eligible',
        ratTransition: 'In Transition',
        ratCompleted: 'Completed',
        ratFromCat: 'From',
        ratToCat: 'To',
        ratSeason: 'Season',
        ratStatus: 'Status',
        ratNoPromotions: 'No promotions',
        ratTop5Info: 'Top 5 players in each category are eligible for promotion',
        ratPromote: 'Promote',
        ratPromoted: 'Player promoted',
        ratStartTransition: 'Start Transition',
        ratCompletePromotion: 'Complete',
        ratCancelPromotion: 'Cancel',
        ratPromotionCancelled: 'Promotion cancelled',
        ratPromotionCompleted: 'Promotion completed, player moved',
        ratConfirmComplete: 'Complete promotion? Player will move to new category, points reset to 0',
        ratConfirmCancel: 'Cancel this promotion?',
        ratActions: 'Actions',
        ratSelectPlayer: 'Select player',
        ratTournamentLevel: 'Tournament Level',
        ratNoLevels: 'Run SQL migration first to create tournament levels',
        ratSearchPlayer: 'Search player...',
        ratSearchTournament: 'Search tournament...',
        ratAllGenders: 'All',
        ratMatchDetails: 'Match Details',
        ratOpponent: 'Opponent',
        ratScore: 'Score',
        ratTournament: 'Tournament',
        ratDate: 'Date',
        ratResult: 'Result',
        ratWin: 'Win',
        ratLoss: 'Loss',
        // Memberships
        memList: 'All Memberships',
        memAdd: 'Add Membership',
        memEdit: 'Edit Membership',
        memUser: 'User',
        memStatus: 'Status',
        memStartsAt: 'Start Date',
        memExpiresAt: 'End Date',
        memDaysLeft: 'Days Left',
        memNote: 'Note',
        memActive: 'Active',
        memExpired: 'Expired',
        memCancelled: 'Cancelled',
        memExtend: 'Extend +1 month',
        memCancel: 'Cancel',
        memExtendConfirm: 'Extend membership by 1 month?',
        memCancelConfirm: 'Cancel this membership?',
        memDeleteConfirm: 'Delete this membership?',
        memNoMembers: 'No memberships yet',
        memNoMembersText: 'Click "Add Membership" to create one',
        memSearch: 'Search by name or email...',
        memAllStatuses: 'All Statuses',
        memSelectUser: '— Select User —',
        memRecordPayment: 'Record payment',
        memPaymentAmount: 'Amount (KGS)',
        memPaymentMethod: 'Method',
        memPaymentCash: 'Cash',
        memPaymentTransfer: 'Bank Transfer',
        memPaymentCard: 'Card',
        memPayments: 'Payment History',
        memPayDate: 'Date',
        memPayAmount: 'Amount',
        memPayMethod: 'Method',
        memPayStatus: 'Status',
        memPayNote: 'Note',
        memNoPayments: 'No payments',
        memExpiringSoon: 'Expiring Soon',
        memPayment: 'Payment',
        memPaid: 'Paid',
        memUnpaid: 'Unpaid',
        memTgConnected: 'TG',
        memProfile: 'Member Profile',
        memPhone: 'Phone',
        memRole: 'Role',
        memRegistered: 'Registered',
        memMembership: 'Membership',
        memDaysLeft: 'Days Left',
        memPaymentHistory: 'Payment History',
        memAmount: 'Amount',
        memDate: 'Date',
        memClose: 'Close',
        // Memberships period + PDF + stats
        memPeriod: 'Period',
        memPrdAll: 'All time',
        memPrdThis: 'This month',
        memPrdLast: 'Last month',
        memPrdCustom: 'Custom',
        memPrdApply: 'Apply',
        memPdfExport: 'Export PDF',
        memPdfTitle: 'KSLT Memberships Report',
        memPdfDate: 'Report date',
        memTotalCount: 'Total',
        memPdfMembers: 'memberships',
        memStatTotal: 'Total Members',
        memStatActiveCount: 'Active',
        memStatExpiredCount: 'Expired',
        memStatExpiringCount: 'Expiring',
        memStatMonthCount: 'This Month',
        // Users
        usrList: 'All Users',
        usrSearch: 'Search by name or email...',
        usrAllRoles: 'All Roles',
        usrEdit: 'Edit User',
        usrProfile: 'Profile',
        usrFullName: 'Full Name',
        usrEmail: 'Email',
        usrPhone: 'Phone',
        usrRole: 'Role',
        usrTelegram: 'Telegram',
        usrTgConnected: 'Connected',
        usrTgNotConnected: 'Not connected',
        usrLastSeen: 'Last Seen',
        usrRegistered: 'Registered',
        usrMembership: 'Membership',
        usrNoMembership: 'No membership',
        usrGiveMembership: 'Give Membership',
        usrExtendMembership: 'Extend',
        usrCancelMembership: 'Cancel Membership',
        usrMembershipPeriod: 'Period',
        usrMonths1: '1 month',
        usrMonths3: '3 months',
        usrMonths6: '6 months',
        usrMonths12: '12 months',
        usrActions: 'Actions',
        usrMakeManager: 'Make Manager',
        usrRemoveManager: 'Remove Manager',
        usrDeleteUser: 'Delete User',
        usrDeleteConfirm: 'Delete this user? This cannot be undone.',
        usrDeleteConfirmTitle: 'Delete User',
        usrCannotDeleteSelf: 'Cannot change your own role',
        usrRoleChanged: 'Role changed',
        usrMembershipGiven: 'Membership activated',
        usrMembershipExtended: 'Membership extended',
        usrMembershipCancelled: 'Membership cancelled',
        usrGiveMembershipTitle: 'Give Membership',
        usrSelectCategory: 'Player Category',
        usrCategoryHint: 'Select category for player card',
        usrPlayerCreated: 'Player card created',
        usrPlayerCategory: 'Player Category',
        usrChangeCategory: 'Change',
        usrCategorySaved: 'Category changed',
        // Ban / Moderation
        usrModeration: 'Moderation',
        usrBanUser: 'Block User',
        usrUnbanUser: 'Unblock',
        usrBanDuration: 'Duration',
        usrBanReason: 'Reason (optional)',
        usrBanConfirm: 'Block this user?',
        usrUnbanConfirm: 'Unblock this user? All restrictions will be removed.',
        usrBanned: 'Blocked',
        usrBannedUntil: 'until',
        usrBannedForever: 'Permanently',
        usrBanSuccess: 'User blocked',
        usrUnbanSuccess: 'User unblocked',
        usrBan1d: '1 day',
        usrBan3d: '3 days',
        usrBan7d: '7 days',
        usrBan30d: '30 days',
        usrBanPermanent: 'Permanently',
        usrThStatus: 'Status',
        usrStatusActive: 'Active',
        usrUserDeleted: 'User deleted',
        usrUserSaved: 'User saved',
        usrNoUsers: 'No users yet',
        usrNoUsersText: 'Users will appear after registration',
        usrAddManager: 'Add Manager',
        usrAddManagerTitle: 'Add Manager',
        usrAddManagerEmail: 'Email',
        usrAddManagerFirstName: 'First Name',
        usrAddManagerLastName: 'Last Name',
        usrAddManagerHint: 'If user exists — role will be updated. If not — invitation will be sent.',
        usrManagerAdded: 'Manager added',
        usrManagerInvited: 'Invitation sent',
        usrThMembership: 'Membership',
        usrOnline: 'Online',
        usrOffline: 'Offline',
        usrActive: 'Active',
        usrExpired: 'Expired',
        usrNone: 'None',
        // Users stats + period + PDF
        usrStatTotal: 'Total Registered',
        usrStatNew: 'New (period)',
        usrStatMembers: 'Active Members',
        usrStatPlayers: 'Linked to Players',
        usrStatAdmins: 'Admins',
        usrStatManagers: 'Managers',
        usrStatRegular: 'Users',
        usrStatTelegram: 'Telegram',
        usrStatBanned: 'Banned',
        usrPeriod: 'Period',
        usrPrdAll: 'All time',
        usrPrdThis: 'This month',
        usrPrdLast: 'Last month',
        usrPrdCustom: 'Custom',
        usrPrdApply: 'Apply',
        usrPdfExport: 'Export PDF',
        usrPdfTitle: 'KSLT Users Report',
        usrPdfDate: 'Report date',
        usrTotalCount: 'Total',
        usrPdfUsers: 'users',
        usrConnected: 'connected',
        usrStatDeleted: 'Deleted',
        usrDeletedAccounts: 'deleted accounts',
        usrChartTitle: 'User Dynamics',
        usrChartRegistered: 'Registered',
        usrChartDeleted: 'Deleted',
        usrChartNet: 'Net Growth',
        // Payments
        payments: 'Payments',
        addPayment: 'Add Payment',
        editPayment: 'Edit Payment',
        payEntityType: 'Entity Type',
        payEntity: 'Payer',
        paySearchEntity: 'Search by name...',
        payAmount: 'Amount',
        payCurrency: 'Currency',
        payPeriodStart: 'Period Start',
        payPeriodEnd: 'Period End',
        payMethod: 'Payment Method',
        payPurpose: 'Purpose',
        payNote: 'Note',
        payStatus: 'Status',
        payActive: 'Active',
        payExpired: 'Expired',
        payAllStatuses: 'All statuses',
        payAllTypes: 'All types',
        payAllPurposes: 'All purposes',
        paySearch: 'Search payments...',
        payCash: 'Cash',
        payTransfer: 'Transfer',
        payCard: 'Card',
        payPromoted: 'Promoted',
        paySponsorship: 'Sponsorship',
        payRental: 'Rental',
        payOther: 'Other',
        payCourt: 'Court',
        payCoach: 'Coach',
        payPlayer: 'Player',
        payNoPayments: 'No payments yet',
        payNoPaymentsText: 'Add the first payment',
        payStatActive: 'Active',
        payStatExpired: 'Expired',
        payStatMonth: 'This Month',
        payCreatedAt: 'Created',
        payEntityRequired: 'Select an entity',
        payAmountRequired: 'Enter the amount',
        payPeriodRequired: 'Enter the period',
        paySaved: 'Payment saved',
        payDeleted: 'Payment deleted',
        payDeleteConfirm: 'Delete this payment?',
        // Payments period + PDF
        payPeriod: 'Period',
        payPrdAll: 'All time',
        payPrdThis: 'This month',
        payPrdLast: 'Last month',
        payPrdCustom: 'Custom',
        payPrdApply: 'Apply',
        payPdfExport: 'Export PDF',
        payPdfTitle: 'KSLT Payments Report',
        payPdfDate: 'Report date',
        payTotalCount: 'Total',
        payTotalAmount: 'Total Amount',
        payPdfPayments: 'payments',
        // Vouchers
        vouchers: 'Vouchers',
        vchTotal: 'Total Issued',
        vchTotalDiscount: 'Total Discounts',
        vchUsed: 'Used',
        vchActive: 'Active',
        vchExpired: 'Expired',
        vchConversion: 'conversion',
        vchCurrency: 'som',
        vchPlayer: 'Player',
        vchServiceType: 'Service Type',
        vchDate: 'Date',
        vchStatus: 'Status',
        vchEntity: 'Court / Coach',
        vchDiscount: 'Discount',
        vchUsedAt: 'Used At',
        vchAllStatuses: 'All statuses',
        vchAllTypes: 'All types',
        vchSearch: 'Search...',
        vchNoVouchers: 'No vouchers yet',
        vchNoVouchersText: 'Vouchers will appear here when members generate them',
        vchPeriod: 'Period',
        vchAllTime: 'All time',
        vchThisMonth: 'This month',
        vchLastMonth: 'Last month',
        vchCustom: 'Custom',
        vchFrom: 'From',
        vchTo: 'To',
        vchApply: 'Apply',
        vchExportPdf: 'Export PDF',
        vchReportTitle: 'KSLT Voucher Report',
        vchCancel: 'Cancel Voucher',
        vchCancelConfirm: 'Cancel this voucher?',
        vchCancelled: 'Voucher cancelled',
        vchTypeCourt: 'Court',
        vchTypeCoach: 'Coach',
        vchStatusActive: 'Active',
        vchStatusUsed: 'Used',
        vchStatusExpired: 'Expired',
        vchStatusCancelled: 'Cancelled',
        vchSortDate: 'Sort by date',
        vchSortName: 'Sort by name',
        vchSortStatus: 'Sort by status',
        vchService: 'Service',
        vchTotal2: 'Total',
        vchReportDate: 'Report date',
        vchVouchers: 'vouchers',
        crtPromotedBadge: 'Promoted',
        crtPromotedHint: 'Managed via Payments section',
        crtViewTitle: 'Court Overview',
        crtViewInfo: 'Information',
        crtViewPayments: 'Payments & Services',
        crtViewNoPayments: 'No payments for this court',
        crtViewEdit: 'Edit',
        crtViewAmount: 'Amount',
        crtViewPurpose: 'Purpose',
        crtViewActiveUntil: 'Active Until',
        crtViewStatus: 'Status',
        crtViewMethod: 'Method',
        // Court partner
        crtPartnerSection: 'KSLT Partnership',
        crtPartnerPin: 'PIN Code',
        crtResetPin: 'Reset',
        crtAddService: '+ Add Service',
        crtServiceName: 'Service Name',
        crtDiscount: 'Discount %',
        crtPartnerHint: 'Partner courts offer discounts to KSLT members',
        crtDefaultService: 'Court Rental',
        // Coach partner
        cchPartnerSection: 'KSLT Partnership',
        cchPartner: 'KSLT Partner',
        cchPartnerPin: 'PIN Code',
        cchResetPin: 'Reset',
        cchAddService: '+ Add Service',
        cchServiceName: 'Service Name',
        cchDiscount: 'Discount %',
        cchDefaultService: 'Training Session',
        // Rating History
        ratingHistory: 'Rating History',
        rhTournament: 'Tournament',
        rhPoints: 'Points',
        rhDate: 'Date',
        rhAdd: 'Add',
        rhNoData: 'No rating history',
        rhTotalPoints: 'Total Points'
    } : {
        dashboard: 'Дашборд',
        users: 'Пользователи',
        tournaments: 'Турниры',
        players: 'Игроки',
        content: 'Новости',
        memberships: 'Членство',
        soon: 'Скоро',
        dashboardTitle: 'Дашборд',
        totalUsers: 'Всего пользователей',
        activeMemberships: 'Активных членств',
        upcomingTournaments: 'Ближайших турниров',
        rankedPlayers: 'Игроков в рейтинге',
        recentRegistrations: 'Последние регистрации',
        thUser: 'Пользователь',
        thEmail: 'Email',
        thRole: 'Роль',
        thDate: 'Дата регистрации',
        roleAdmin: 'Администратор',
        roleManager: 'Менеджер',
        rolePlayer: 'Игрок',
        roleUser: 'Пользователь',
        comingSoonTitle: 'В разработке',
        comingSoonText: 'Этот раздел находится в разработке',
        noData: '—',
        iconUsers: '👥',
        iconMemberships: '💳',
        iconTournaments: '🏆',
        iconPlayers: '📊',
        // Dashboard cards
        iconOverdue: '⚠️',
        iconApproaching: '⏰',
        iconNews: '📰',
        statMembersDetail: 'членов / пользователей',
        statOverdueDetail: 'просроченных членств',
        statApproachingDetail: 'истекает в ближ. 10 дней',
        statTournamentsDetail: 'прошло / предстоит',
        statNewsDetail: 'статей опубликовано',
        // Dashboard activity tables
        actApproaching: 'Скоро оплата',
        actOverdue: 'Просроченные оплаты',
        actRecentRegistrations: 'Последние регистрации',
        actRecentTournaments: 'Последние турниры',
        actRecentNews: 'Последние новости',
        dashChartTitle: 'Прирост пользователей (12 мес.)',
        dashChartRegistered: 'Зарегистрировано',
        dashChartDeleted: 'Удалено',
        dashChartNet: 'Нетто',
        viewAll: 'Все',
        thName: 'Имя',
        thExpires: 'Истекает',
        thDaysLeft: 'Осталось',
        thOverdueDays: 'Просрочка',
        thTournament: 'Турнир',
        thDateStart: 'Дата',
        thArticle: 'Статья',
        thStatus: 'Статус',
        iconPending: '📋',
        iconCourts: '🏟️',
        iconCoaches: '🎓',
        iconManagers: '👔',
        statPendingDetail: 'заявок на турниры',
        statCourtsDetail: 'кортов всего',
        statCoachesDetail: 'тренеров всего',
        statManagersDetail: 'менеджеров',
        actPendingRegs: 'Ожидают одобрения',
        thPlayer: 'Игрок',
        thCategory: 'Категория',
        noPendingRegs: 'Нет заявок на одобрение',
        noApproaching: 'Нет истекающих членств',
        noOverdue: 'Нет просроченных оплат',
        noRecentUsers: 'Нет новых регистраций',
        noRecentTournaments: 'Нет последних турниров',
        noRecentNews: 'Нет последних новостей',
        // News
        addNews: 'Добавить статью',
        editNews: 'Редактировать статью',
        newsList: 'Все статьи',
        newsTitle: 'Заголовок',
        newsSlug: 'Slug (URL)',
        newsExcerpt: 'Краткое описание',
        newsContent: 'Содержание',
        newsImage: 'Обложка',
        newsCategory: 'Категория',
        newsAuthor: 'Автор',
        newsPublishedAt: 'Дата публикации',
        newsDraft: 'Черновик',
        newsPublished: 'Опубликовано',
        newsSearch: 'Поиск по заголовку...',
        newsAll: 'Все',
        save: 'Сохранить',
        saving: 'Сохранение...',
        saved: 'Сохранено!',
        delete: 'Удалить',
        deleteSelected: 'Удалить выбранные',
        deleteSelectedConfirm: 'Удалить выбранные элементы?',
        deleteConfirm: 'Удалить эту статью?',
        deleteConfirmText: 'Это действие нельзя отменить.',
        cancel: 'Отмена',
        back: 'Назад к списку',
        uploadImage: 'Нажмите для загрузки или перетащите изображение',
        uploadHint: 'JPG или PNG, до 2 МБ',
        orPasteUrl: 'Или вставьте URL изображения',
        applyUrl: 'Применить',
        publish: 'Опубликовать',
        update: 'Обновить',
        newsGallery: 'Галерея',
        contentPreview: 'Предпросмотр',
        insertPhoto: '+ Фото',
        pollSection: 'Голосование',
        pollQuestion: 'Вопрос',
        pollOption: 'Вариант',
        pollAdd: '+ Добавить вариант',
        pollEnable: 'Добавить голосование',
        pollRemove: 'Убрать голосование',
        thReactions: 'Реакции',
        thVotes: 'Голоса',
        engagement: 'Вовлечённость',
        totalVotes: 'Всего голосов',
        newsStatPublished: 'Опубликовано',
        newsStatDrafts: 'Черновики',
        newsStatPopular: 'Популярные',
        newsStatLastDate: 'Последняя',
        newsStatNoArticles: 'Статей пока нет',
        catResults: 'Репортаж',
        catInterview: 'Интервью',
        catAnnouncement: 'Анонс',
        catWorld: 'Мировой теннис',
        selectCategory: '— Выберите —',
        slugHint: 'Генерируется из заголовка. Используется в URL.',
        translateBtn: 'Перевести с RU',
        translating: 'Перевод...',
        translateError: 'Ошибка перевода',
        fillRuFirst: 'Сначала заполните поле RU',
        fillAnyLang: 'Заполните на любом языке',
        textCopied: 'Текст скопирован',
        metaReadTime: 'мин чтения',
        translateFromAny: 'Перевести',
        noArticles: 'Статей пока нет',
        noArticlesText: 'Нажмите "Добавить статью" чтобы создать первую статью',
        thTitle: 'Заголовок',
        thCategory: 'Категория',
        thStatus: 'Статус',
        thPublished: 'Дата',
        thPubDate: 'Дата публикации',
        thViews: 'Просмотры',
        thExecutor: 'Исполнитель',
        newsExecutor: 'Исполнитель',
        draftSaved: 'Черновик сохранён',
        unsavedChanges: 'Несохранённые изменения',
        unsavedChangesText: 'Есть несохранённые изменения. Выйти без сохранения?',
        unsavedLeaveBtn: 'Выйти',
        // Tournaments
        addTournament: 'Добавить турнир',
        editTournament: 'Редактировать турнир',
        trnTitle: 'Название',
        trnDescription: 'Описание',
        trnLocation: 'Место проведения',
        trnCategory: 'Категория',
        trnStatus: 'Статус',
        trnDateStart: 'Дата начала',
        trnDateEnd: 'Дата окончания',
        trnDateEndShort: 'Дата оконч.',
        trnMaxParticipants: 'Макс. участников',
        trnMaxParticipantsShort: 'Макс. участ.',
        trnPrizeFund: 'Призовой фонд',
        trnImage: 'Обложка',
        noTournaments: 'Турниров пока нет',
        noTournamentsText: 'Нажмите "Добавить турнир" чтобы создать первый турнир',
        trnDeleteConfirm: 'Удалить этот турнир?',
        trnDraft: 'Черновик',
        trnCancelTournament: 'Отменить турнир',
        trnCancelConfirm: 'Отменить этот турнир? Он будет помечен как отменённый.',
        trnNotify: 'Рассылка в Telegram',
        trnNotifySent: 'Отправлено',
        trnNotifyConfirm: 'Отправить анонс турнира в Telegram-группу?',
        trnNotifyBtn: 'Отправить',
        statusUpcoming: 'Предстоящий',
        statusRegOpen: 'Регистрация открыта',
        statusRegClosed: 'Регистрация закрыта',
        statusOngoing: 'Идёт',
        statusCompleted: 'Завершён',
        statusCancelled: 'Отменён',
        selectStatus: '— Выберите —',
        selectCategoryTrn: '— Выберите —',
        trnFormat: 'Формат',
        formatSingles: 'Одиночный',
        formatDoubles: 'Парный',
        formatMixedDoubles: 'Смешанный парный',
        selectFormat: '— Выберите —',
        genderMen: 'Мужской',
        genderWomen: 'Женский',
        trnDrawSize: 'Размер сетки',
        trnBracketType: 'Тип сетки',
        trnCourtCount: 'Корты',
        trnMatchDuration: 'Длит. матча (мин)',
        trnStartTime: 'Время начала',
        trnBuffer: 'Буфер (мин)',
        trnRegStart: 'Начало регистрации',
        trnRegEnd: 'Конец регистрации',
        trnVenue: 'Место проведения',
        trnVenueSearch: 'Введите название корта...',
        trnVenueClear: 'Сбросить',
        trnVenueAddress: 'Адрес',
        trnVenuePhone: 'Телефон',
        trnVenueMap: 'Карта',
        bracketSE: 'Олимпийская',
        bracketFIC: 'Олимпийская (все места)',
        bracketRR: 'Групповая',
        trnGroupCount: 'Количество групп',
        trnQualifiers: 'Выходят из группы',
        generatePlayoff: 'Сформировать плей-офф',
        generatePlayoffConfirm: 'Сформировать сетку плей-офф из победителей групп?',
        playoffTitle: 'Плей-офф',
        groupStageTitle: 'Групповой этап',
        groupLabel: 'Группа',
        groupPoints: 'Очки',
        groupPlace: 'Место',
        groupWins: 'П',
        groupLosses: 'Пр',
        selectDrawSize: '— Выберите —',
        selectBracketType: '— Выберите —',
        trnStatTotal: 'Всего турниров',
        trnStatUpcoming: 'Предстоящие',
        trnStatCompleted: 'Прошедшие',
        trnStatMenSingles: 'Мужские одиночные',
        trnStatWomenSingles: 'Женские одиночные',
        trnStatMenDoubles: 'Мужские парные',
        trnStatWomenDoubles: 'Женские парные',
        trnStatFriendly: 'Дружеские',
        trnSearch: 'Поиск по названию...',
        trnAllCategories: 'Все категории',
        trnAllStatuses: 'Все статусы',
        // Bracket management
        bracketTab: 'Сетка',
        registrationsTab: 'Заявки',
        scheduleTab: 'Расписание',
        resultsTab: 'Результаты',
        trnTabEdit: 'Редактирование',
        trnTabRegs: 'Заявки',
        trnTabBracket: 'Сетка',
        trnTabSchedule: 'Расписание',
        trnTabPoints: 'Результаты',
        schedTime: 'Время',
        schedCourt: 'Корт',
        schedMatch: 'Матч',
        schedRound: 'Раунд',
        schedSave: 'Сохранить расписание',
        schedSaved: 'Расписание сохранено',
        schedCourtTitle: 'Корт',
        resPlace: 'Место',
        resPlayer: 'Игрок',
        resRound: 'Раунд',
        resPoints: 'Очки',
        resTotalPlayers: 'Всего игроков',
        generateDraw: 'Сгенерировать сетку',
        generateDrawConfirm: 'Сгенерировать сетку? Регистрация будет закрыта.',
        drawGenerated: 'Сетка успешно сгенерирована',
        noRegistrations: 'Заявок пока нет',
        regStatus: 'Статус',
        regApprove: 'Одобрить',
        regReject: 'Отклонить',
        regApproved: 'Одобрена',
        regRejected: 'Отклонена',
        regPending: 'Ожидает',
        regWithdrawn: 'Отозвана',
        regCount: 'зарегистрировано',
        regMainDraw: 'Основная сетка',
        regWaitlist: 'Лист ожидания',
        regRemoveSelected: 'Удалить выбранных',
        regRemoveConfirm: 'Удалить выбранных участников?',
        regNoWaitlist: 'Нет игроков в листе ожидания',
        regWaitlistInfo: 'Ожидает одобрения',
        enterScore: 'Ввести счёт',
        saveScore: 'Сохранить счёт',
        addSet: '+ Добавить сет',
        removeSet: '- Убрать сет',
        matchScore: 'Счёт',
        matchWinner: 'Победитель',
        matchCompleted: 'завершён',
        matchUpcoming: 'предстоит',
        matchLive: 'идёт',
        finalizeTournament: 'Завершить турнир',
        finalizeConfirm: 'Завершить турнир? Очки будут рассчитаны для всех игроков.',
        tournamentFinalized: 'Турнир завершён. Очки рассчитаны.',
        regenerateDraw: 'Пересоздать жеребьёвку',
        regenerateConfirm: 'Пересоздать жеребьёвку? Все текущие матчи будут удалены и создан новый посев из текущих заявок.',
        seedLabel: 'Посев',
        byeLabel: 'BYE',
        vsLabel: 'vs',
        roundR1: '1-й раунд',
        roundQF: 'Четвертьфинал',
        roundSF: 'Полуфинал',
        roundF: 'Финал',
        round3rd: 'За 3-е место',
        roundR16: '1/8 финала',
        // Players
        addPlayer: 'Добавить игрока',
        editPlayer: 'Редактировать игрока',
        plrName: 'Имя',
        plrCountry: 'Страна',
        plrCategory: 'Категория',
        plrPoints: 'Очки',
        plrWins: 'Победы',
        plrLosses: 'Поражения',
        plrRankChange: 'Динамика',
        plrForm: 'Последняя форма',
        plrBadges: 'Достижения',
        badgeEarned: 'Получен',
        badgeLocked: 'Заблокирован',
        badgeHowTo: 'Как получить',
        badgeManualAward: 'Выдать бейдж',
        badgeRemove: 'Убрать',
        badgeNewToast: 'Новый бейдж',
        badgeCheckBtn: 'Проверить бейджи',
        badgeNoEarned: 'Бейджей пока нет',
        plrBio: 'Биография',
        plrPhone: 'Телефон',
        plrEmail: 'Email',
        plrPhoto: 'Фото',
        plrShowPhone: 'Показывать телефон',
        noPlayers: 'Игроков пока нет',
        noPlayersText: 'Нажмите "Добавить игрока" для создания',
        plrDeleteConfirm: 'Удалить этого игрока?',
        plrSearch: 'Поиск по имени...',
        plrAllCategories: 'Все категории',
        badgeChampion: 'Чемпион',
        badgeTop1: 'Топ 1',
        badgeStreak: 'Серия побед',
        badgeNewbie: 'Новичок',
        badgeBreakthrough: 'Прорыв',
        thPoints: 'Очки',
        thWL: 'В/П',
        thChange: 'Динамика',
        // Courts
        courts: 'Корты',
        addCourt: 'Добавить корт',
        editCourt: 'Редактировать корт',
        crtName: 'Название',
        crtType: 'Тип',
        crtSurface: 'Покрытие',
        crtCourtsCount: 'Кол-во',
        crtPrice: 'Цена<br><span style="font-size:0.65rem;font-weight:400;color:var(--text-dim);">(сом/час)</span>',
        crtMobile: 'Мобильный',
        crtLandline: 'Стационарный',
        crtAddPhone: '+ Добавить телефон',
        crtEmail: 'Email',
        crtDescription: 'Описание',
        crtAmenities: 'Удобства',
        crtPartner: 'Партнёр',
        crtPromoted: 'Promoted',
        crtPhoto: 'Главное фото',
        crtGallery: 'Галерея',
        crtGoogleMaps: 'Google Maps',
        crtTwoGis: '2GIS',
        crtStreet: 'Улица',
        crtBuilding: 'Номер',
        crtDistrict: 'Район / Ориентир',
        crtCity: 'Город',
        crtPostalCode: 'Индекс',
        crtSlogan: 'Дополнительно',
        crtAdd: '+ Добавить',
        noCourts: 'Кортов пока нет',
        noCourtsText: 'Нажмите "Добавить корт" для создания',
        crtDeleteConfirm: 'Удалить этот корт?',
        crtSearch: 'Поиск по названию...',
        crtAllTypes: 'Все типы',
        crtStatOutdoor: 'Открытые',
        crtStatIndoor: 'Закрытые',
        crtStatTotal: 'Всего',
        crtAllSurfaces: 'Все покрытия',
        crtOther: 'Другое',
        crtCustomAmenity: 'Своё удобство',
        crtAddCustom: '+ Добавить своё',
        crtAddByUrl: '+ По ссылке',
        translateAllBtn: 'Перевести в пустые',
        allFieldsFilled: 'Все поля уже заполнены',
        // Coaches
        coaches: 'Тренеры',
        addCoach: 'Добавить тренера',
        editCoach: 'Редактировать тренера',
        cchLastName: 'Фамилия',
        cchFirstName: 'Имя',
        cchPatronymic: 'Отчество',
        cchPosition: 'Должность',
        cchTags: 'Теги',
        cchExperience: 'Опыт (лет)',
        cchPrice: 'Цена (сом/час)',
        cchShortDesc: 'Краткое описание',
        cchBio: 'Биография',
        cchAchievements: 'Достижения',
        cchAchievementAdd: '+ Добавить достижение',
        cchCourt: 'Корт / Клуб',
        cchPhone: 'Телефон (внутренний)',
        cchTelegram: 'Telegram',
        cchWhatsapp: 'WhatsApp',
        cchPhoto: 'Фото',
        noCoaches: 'Тренеров пока нет',
        noCoachesText: 'Нажмите "Добавить тренера" для создания',
        cchDeleteConfirm: 'Удалить этого тренера?',
        cchSearch: 'Поиск по имени...',
        cchAllTags: 'Все теги',
        cchPromoted: 'Promoted',
        cchStatTotal: 'Всего тренеров',
        cchStatPromoted: 'Продвигаются',
        cchStatNew: 'Новые за месяц',
        cchViewTitle: 'Обзор тренера',
        cchViewInfo: 'Информация',
        cchViewPayments: 'Оплаты и услуги',
        cchViewNoPayments: 'Нет оплат по этому тренеру',
        cchViewEdit: 'Редактировать',
        cchPromotedBadge: 'Продвигается',
        cchPromotedHint: 'Управляется через раздел Оплаты',
        // Ratings
        ratings: 'Рейтинг',
        ratSubRankings: 'Рейтинги',
        ratSubResults: 'Результаты',
        ratSubRules: 'Правила очков',
        ratSubPromotions: 'Промоушен',
        ratSelectCategory: 'Выберите категорию',
        ratAllCategories: 'Все категории',
        ratRank: '#',
        ratPlayer: 'Игрок',
        ratPoints: 'Очки',
        ratWL: 'В/П',
        ratForm: 'Форма',
        ratNoPlayers: 'Нет игроков в этой категории',
        ratSelectTournament: 'Выберите турнир',
        ratCompletedOnly: 'Только завершённые турниры',
        ratRound: 'Раунд',
        ratPointsEarned: 'Очки',
        ratAddResult: '+ Добавить результат',
        ratSaveResults: 'Сохранить результаты',
        ratNoResults: 'Результатов пока нет',
        ratLevel: 'Уровень турнира',
        ratW: 'Победитель',
        ratF: 'Финалист',
        rat3RD: '3-е место',
        rat4TH: '4-е место',
        ratSF: 'Полуфинал',
        ratQF: 'Четвертьфинал',
        ratR16: '1/8 финала',
        ratR32: '1/16 финала',
        ratG3: '3-е в группе',
        ratG4: '4-е в группе',
        ratG5: '5-е в группе',
        ratG6: '6-е в группе',
        ratSaveRules: 'Сохранить правила',
        ratAddLevel: '+ Добавить уровень',
        ratLevelName: 'Название уровня',
        ratLevelNameEn: 'Название уровня (EN)',
        ratDeleteLevel: 'Удалить уровень',
        ratDeleteLevelConfirm: 'Удалить этот уровень и все его правила?',
        ratLevelAdded: 'Уровень добавлен',
        ratLevelDeleted: 'Уровень удалён',
        ratRulesSaved: 'Правила очков сохранены',
        ratResultsSaved: 'Результаты сохранены, очки пересчитаны',
        ratEligible: 'Доступен',
        ratTransition: 'Переходный период',
        ratCompleted: 'Завершён',
        ratFromCat: 'Из',
        ratToCat: 'В',
        ratSeason: 'Сезон',
        ratStatus: 'Статус',
        ratNoPromotions: 'Нет промоушенов',
        ratTop5Info: 'Топ-5 игроков каждой категории могут перейти на уровень выше',
        ratPromote: 'Промоутить',
        ratPromoted: 'Игрок промоутирован',
        ratStartTransition: 'Начать переход',
        ratCompletePromotion: 'Завершить',
        ratCancelPromotion: 'Отменить',
        ratPromotionCancelled: 'Промоушен отменён',
        ratPromotionCompleted: 'Промоушен завершён, игрок переведён',
        ratConfirmComplete: 'Завершить промоушен? Игрок перейдёт в новую категорию, очки обнулятся',
        ratConfirmCancel: 'Отменить промоушен?',
        ratActions: 'Действия',
        ratSelectPlayer: 'Выберите игрока',
        ratTournamentLevel: 'Уровень турнира',
        ratNoLevels: 'Сначала выполните SQL миграцию для создания уровней турниров',
        ratSearchPlayer: 'Поиск игрока...',
        ratSearchTournament: 'Поиск турнира...',
        ratAllGenders: 'Все',
        ratMatchDetails: 'Детали матча',
        ratOpponent: 'Противник',
        ratScore: 'Счёт',
        ratTournament: 'Турнир',
        ratDate: 'Дата',
        ratResult: 'Результат',
        ratWin: 'Победа',
        ratLoss: 'Поражение',
        // Memberships
        memList: 'Все членства',
        memAdd: 'Добавить членство',
        memEdit: 'Редактировать членство',
        memUser: 'Пользователь',
        memStatus: 'Статус',
        memStartsAt: 'Дата начала',
        memExpiresAt: 'Дата окончания',
        memDaysLeft: 'Осталось дней',
        memNote: 'Заметка',
        memActive: 'Активно',
        memExpired: 'Истекло',
        memCancelled: 'Отменено',
        memExtend: 'Продлить +1 мес',
        memCancel: 'Отменить',
        memExtendConfirm: 'Продлить членство на 1 месяц?',
        memCancelConfirm: 'Отменить это членство?',
        memDeleteConfirm: 'Удалить это членство?',
        memNoMembers: 'Членств пока нет',
        memNoMembersText: 'Нажмите "Добавить членство" для создания',
        memSearch: 'Поиск по имени или email...',
        memAllStatuses: 'Все статусы',
        memSelectUser: '— Выберите пользователя —',
        memRecordPayment: 'Записать оплату',
        memPaymentAmount: 'Сумма (KGS)',
        memPaymentMethod: 'Способ оплаты',
        memPaymentCash: 'Наличные',
        memPaymentTransfer: 'Банковский перевод',
        memPaymentCard: 'Карта',
        memPayments: 'История платежей',
        memPayDate: 'Дата',
        memPayAmount: 'Сумма',
        memPayMethod: 'Способ',
        memPayStatus: 'Статус',
        memPayNote: 'Заметка',
        memNoPayments: 'Платежей нет',
        memExpiringSoon: 'Скоро истекает',
        memPayment: 'Оплата',
        memPaid: 'Оплачено',
        memUnpaid: 'Не оплачено',
        memTgConnected: 'TG',
        memProfile: 'Профиль участника',
        memPhone: 'Телефон',
        memRole: 'Роль',
        memRegistered: 'Дата регистрации',
        memMembership: 'Членство',
        memDaysLeft: 'Дней осталось',
        memPaymentHistory: 'История оплат',
        memAmount: 'Сумма',
        memDate: 'Дата',
        memClose: 'Закрыть',
        // Memberships period + PDF + stats
        memPeriod: 'Период',
        memPrdAll: 'Всё время',
        memPrdThis: 'Этот месяц',
        memPrdLast: 'Прошлый месяц',
        memPrdCustom: 'Свой период',
        memPrdApply: 'Применить',
        memPdfExport: 'Экспорт PDF',
        memPdfTitle: 'KSLT — Отчёт по членству',
        memPdfDate: 'Дата отчёта',
        memTotalCount: 'Итого',
        memPdfMembers: 'записей',
        memStatTotal: 'Всего участников',
        memStatActiveCount: 'Активных',
        memStatExpiredCount: 'Просроченных',
        memStatExpiringCount: 'Истекающих',
        memStatMonthCount: 'За этот месяц',
        // Users
        usrList: 'Все пользователи',
        usrSearch: 'Поиск по имени или email...',
        usrAllRoles: 'Все роли',
        usrEdit: 'Редактировать пользователя',
        usrProfile: 'Профиль',
        usrFullName: 'Полное имя',
        usrEmail: 'Email',
        usrPhone: 'Телефон',
        usrRole: 'Роль',
        usrTelegram: 'Telegram',
        usrTgConnected: 'Подключён',
        usrTgNotConnected: 'Не подключён',
        usrLastSeen: 'Последний визит',
        usrRegistered: 'Дата регистрации',
        usrMembership: 'Членство',
        usrNoMembership: 'Нет членства',
        usrGiveMembership: 'Выдать членство',
        usrExtendMembership: 'Продлить',
        usrCancelMembership: 'Отменить членство',
        usrMembershipPeriod: 'Период',
        usrMonths1: '1 месяц',
        usrMonths3: '3 месяца',
        usrMonths6: '6 месяцев',
        usrMonths12: '12 месяцев',
        usrActions: 'Действия',
        usrMakeManager: 'Сделать менеджером',
        usrRemoveManager: 'Убрать менеджера',
        usrDeleteUser: 'Удалить пользователя',
        usrDeleteConfirm: 'Удалить пользователя? Это действие нельзя отменить.',
        usrDeleteConfirmTitle: 'Удаление пользователя',
        usrCannotDeleteSelf: 'Нельзя изменить свою роль',
        usrRoleChanged: 'Роль изменена',
        usrMembershipGiven: 'Членство активировано',
        usrMembershipExtended: 'Членство продлено',
        usrMembershipCancelled: 'Членство отменено',
        usrGiveMembershipTitle: 'Выдать членство',
        usrSelectCategory: 'Категория игрока',
        usrCategoryHint: 'Выберите категорию для карточки игрока',
        usrPlayerCreated: 'Карточка игрока создана',
        usrPlayerCategory: 'Категория игрока',
        usrChangeCategory: 'Изменить',
        usrCategorySaved: 'Категория изменена',
        // Ban / Moderation
        usrModeration: 'Модерация',
        usrBanUser: 'Заблокировать',
        usrUnbanUser: 'Разблокировать',
        usrBanDuration: 'Срок',
        usrBanReason: 'Причина (необязательно)',
        usrBanConfirm: 'Заблокировать пользователя?',
        usrUnbanConfirm: 'Разблокировать пользователя? Все ограничения будут сняты.',
        usrBanned: 'Заблокирован',
        usrBannedUntil: 'до',
        usrBannedForever: 'Навсегда',
        usrBanSuccess: 'Пользователь заблокирован',
        usrUnbanSuccess: 'Пользователь разблокирован',
        usrBan1d: '1 день',
        usrBan3d: '3 дня',
        usrBan7d: '7 дней',
        usrBan30d: '30 дней',
        usrBanPermanent: 'Навсегда',
        usrThStatus: 'Статус',
        usrStatusActive: 'Активен',
        usrUserDeleted: 'Пользователь удалён',
        usrUserSaved: 'Пользователь сохранён',
        usrNoUsers: 'Пользователей пока нет',
        usrNoUsersText: 'Пользователи появятся после регистрации',
        usrAddManager: 'Добавить менеджера',
        usrAddManagerTitle: 'Добавить менеджера',
        usrAddManagerEmail: 'Email',
        usrAddManagerFirstName: 'Имя',
        usrAddManagerLastName: 'Фамилия',
        usrAddManagerHint: 'Если пользователь есть — обновится роль. Если нет — будет отправлено приглашение.',
        usrManagerAdded: 'Менеджер добавлен',
        usrManagerInvited: 'Приглашение отправлено',
        usrThMembership: 'Членство',
        usrOnline: 'Онлайн',
        usrOffline: 'Офлайн',
        usrActive: 'Активно',
        usrExpired: 'Истекло',
        usrNone: 'Нет',
        // Users stats + period + PDF
        usrStatTotal: 'Всего зарегистрировано',
        usrStatNew: 'Новых (период)',
        usrStatMembers: 'С активным членством',
        usrStatPlayers: 'Привязано к игрокам',
        usrStatAdmins: 'Админов',
        usrStatManagers: 'Менеджеров',
        usrStatRegular: 'Пользователей',
        usrStatTelegram: 'Telegram',
        usrStatBanned: 'Забанено',
        usrPeriod: 'Период',
        usrPrdAll: 'Всё время',
        usrPrdThis: 'Этот месяц',
        usrPrdLast: 'Прошлый месяц',
        usrPrdCustom: 'Свой период',
        usrPrdApply: 'Применить',
        usrPdfExport: 'Экспорт PDF',
        usrPdfTitle: 'KSLT — Отчёт по пользователям',
        usrPdfDate: 'Дата отчёта',
        usrTotalCount: 'Итого',
        usrPdfUsers: 'пользователей',
        usrConnected: 'подключено',
        usrStatDeleted: 'Удалено',
        usrDeletedAccounts: 'удалённых аккаунтов',
        usrChartTitle: 'Динамика пользователей',
        usrChartRegistered: 'Зарегистрировано',
        usrChartDeleted: 'Удалено',
        usrChartNet: 'Прирост',
        // Payments
        payments: 'Оплаты',
        addPayment: 'Добавить оплату',
        editPayment: 'Редактировать оплату',
        payEntityType: 'Тип объекта',
        payEntity: 'Плательщик',
        paySearchEntity: 'Поиск по названию...',
        payAmount: 'Сумма',
        payCurrency: 'Валюта',
        payPeriodStart: 'Начало периода',
        payPeriodEnd: 'Конец периода',
        payMethod: 'Способ оплаты',
        payPurpose: 'Назначение',
        payNote: 'Примечание',
        payStatus: 'Статус',
        payActive: 'Активна',
        payExpired: 'Истекла',
        payAllStatuses: 'Все статусы',
        payAllTypes: 'Все типы',
        payAllPurposes: 'Все назначения',
        paySearch: 'Поиск оплат...',
        payCash: 'Наличные',
        payTransfer: 'Перевод',
        payCard: 'Карта',
        payPromoted: 'Продвижение',
        paySponsorship: 'Спонсорство',
        payRental: 'Аренда',
        payOther: 'Другое',
        payCourt: 'Корт',
        payCoach: 'Тренер',
        payPlayer: 'Игрок',
        payNoPayments: 'Оплат пока нет',
        payNoPaymentsText: 'Добавьте первую оплату',
        payStatActive: 'Активных',
        payStatExpired: 'Просроченных',
        payStatMonth: 'За этот месяц',
        payCreatedAt: 'Создано',
        payEntityRequired: 'Выберите объект',
        payAmountRequired: 'Введите сумму',
        payPeriodRequired: 'Укажите период',
        paySaved: 'Оплата сохранена',
        payDeleted: 'Оплата удалена',
        payDeleteConfirm: 'Удалить эту оплату?',
        // Payments period + PDF
        payPeriod: 'Период',
        payPrdAll: 'Всё время',
        payPrdThis: 'Этот месяц',
        payPrdLast: 'Прошлый месяц',
        payPrdCustom: 'Свой период',
        payPrdApply: 'Применить',
        payPdfExport: 'Экспорт PDF',
        payPdfTitle: 'KSLT — Отчёт по оплатам',
        payPdfDate: 'Дата отчёта',
        payTotalCount: 'Итого',
        payTotalAmount: 'Общая сумма',
        payPdfPayments: 'оплат',
        // Vouchers
        vouchers: 'Ваучеры',
        vchTotal: 'Всего выдано',
        vchTotalDiscount: 'Сумма скидок',
        vchUsed: 'Использовано',
        vchActive: 'Активных',
        vchExpired: 'Истекло',
        vchConversion: 'конверсия',
        vchCurrency: 'сом',
        vchPlayer: 'Игрок',
        vchServiceType: 'Тип услуги',
        vchDate: 'Дата',
        vchStatus: 'Статус',
        vchEntity: 'Корт / Тренер',
        vchDiscount: 'Скидка',
        vchUsedAt: 'Использован',
        vchAllStatuses: 'Все статусы',
        vchAllTypes: 'Все типы',
        vchSearch: 'Поиск...',
        vchNoVouchers: 'Ваучеров пока нет',
        vchNoVouchersText: 'Ваучеры появятся здесь, когда участники начнут их генерировать',
        vchPeriod: 'Период',
        vchAllTime: 'Всё время',
        vchThisMonth: 'Этот месяц',
        vchLastMonth: 'Прошлый месяц',
        vchCustom: 'Свой период',
        vchFrom: 'С',
        vchTo: 'По',
        vchApply: 'Применить',
        vchExportPdf: 'Экспорт PDF',
        vchReportTitle: 'KSLT — Отчёт по ваучерам',
        vchCancel: 'Отменить ваучер',
        vchCancelConfirm: 'Отменить этот ваучер?',
        vchCancelled: 'Ваучер отменён',
        vchTypeCourt: 'Корт',
        vchTypeCoach: 'Тренер',
        vchStatusActive: 'Активный',
        vchStatusUsed: 'Использован',
        vchStatusExpired: 'Истёк',
        vchStatusCancelled: 'Отменён',
        vchSortDate: 'По дате',
        vchSortName: 'По имени',
        vchSortStatus: 'По статусу',
        vchService: 'Услуга',
        vchTotal2: 'Итого',
        vchReportDate: 'Дата отчёта',
        vchVouchers: 'ваучеров',
        crtPromotedBadge: 'Продвигается',
        crtPromotedHint: 'Управляется через раздел Оплаты',
        crtViewTitle: 'Обзор корта',
        crtViewInfo: 'Информация',
        crtViewPayments: 'Оплаты и услуги',
        crtViewNoPayments: 'Нет оплат по этому корту',
        crtViewEdit: 'Редактировать',
        crtViewAmount: 'Сумма',
        crtViewPurpose: 'Назначение',
        crtViewActiveUntil: 'Активен до',
        crtViewStatus: 'Статус',
        crtViewMethod: 'Способ',
        // Court partner
        crtPartnerSection: 'Партнёрство KSLT',
        crtPartnerPin: 'PIN-код',
        crtResetPin: 'Сбросить',
        crtAddService: '+ Добавить услугу',
        crtServiceName: 'Название услуги',
        crtDiscount: 'Скидка %',
        crtPartnerHint: 'Партнёрские корты дают скидки членам KSLT',
        crtDefaultService: 'Аренда корта',
        // Coach partner
        cchPartnerSection: 'Партнёрство KSLT',
        cchPartner: 'Партнёр KSLT',
        cchPartnerPin: 'PIN-код',
        cchResetPin: 'Сбросить',
        cchAddService: '+ Добавить услугу',
        cchServiceName: 'Название услуги',
        cchDiscount: 'Скидка %',
        cchDefaultService: 'Тренировка',
        // Rating History
        ratingHistory: 'История рейтинга',
        rhTournament: 'Турнир',
        rhPoints: 'Очки',
        rhDate: 'Дата',
        rhAdd: 'Добавить',
        rhNoData: 'Нет данных',
        rhTotalPoints: 'Всего очков'
    };

    // Category map
    var CATEGORIES = {
        results: isEn ? 'Report' : 'Репортаж',
        interview: isEn ? 'Interview' : 'Интервью',
        announcement: isEn ? 'Announcement' : 'Анонс',
        world: isEn ? 'World Tennis' : 'Мировой теннис'
    };

    // ---- Tournament Maps ----
    var cachedCategories = [];
    var categoriesMap = {};

    async function loadCategories() {
        if (cachedCategories.length > 0) return;
        if (!client) return;
        var result = await client.from('categories').select('*').order('sort_order', { ascending: true });
        cachedCategories = result.data || [];
        cachedCategories.forEach(function(c) {
            categoriesMap[c.id] = c;
        });
    }

    var TOURNAMENT_FORMATS = {
        singles: L.formatSingles,
        doubles: L.formatDoubles,
        mixed_doubles: L.formatMixedDoubles
    };

    var COURT_TYPES = {
        indoor: isEn ? 'Indoor' : 'Крытый',
        outdoor: isEn ? 'Outdoor' : 'Открытый'
    };

    var COURT_SURFACES = {
        hard: isEn ? 'Hard' : 'Хард',
        clay: isEn ? 'Clay' : 'Грунт',
        carpet: isEn ? 'Carpet' : 'Ковёр'
    };

    var COURT_AMENITIES = [
        { key: 'locker_rooms', label: isEn ? 'Locker Rooms' : 'Раздевалки' },
        { key: 'showers', label: isEn ? 'Showers' : 'Душевые' },
        { key: 'parking', label: isEn ? 'Parking' : 'Парковка' },
        { key: 'racket_rental', label: isEn ? 'Racket Rental' : 'Прокат ракеток' },
        { key: 'pro_shop', label: 'Pro-shop' },
        { key: 'cafe', label: isEn ? 'Café' : 'Кафе' },
        { key: 'gym', label: isEn ? 'Gym' : 'Тренажёрный зал' },
        { key: 'pool', label: isEn ? 'Swimming Pool' : 'Бассейн' },
        { key: 'sauna', label: isEn ? 'Sauna' : 'Сауна' },
        { key: 'climate', label: isEn ? 'Climate Control' : 'Климат-контроль' },
        { key: 'lighting', label: isEn ? 'Night Lighting' : 'Вечернее освещение' },
        { key: 'kids_area', label: isEn ? 'Kids Area' : 'Детская площадка' },
        { key: 'kids_school', label: isEn ? 'Kids School' : 'Детская школа' },
        { key: 'video', label: isEn ? 'Video Analysis' : 'Видеоанализ' },
        { key: 'wifi', label: 'Wi-Fi' },
        { key: 'benches', label: isEn ? 'Benches' : 'Скамейки' }
    ];

    var TOURNAMENT_STATUSES = {
        upcoming: L.statusUpcoming,
        registration_open: L.statusRegOpen,
        registration_closed: L.statusRegClosed,
        ongoing: L.statusOngoing,
        completed: L.statusCompleted,
        cancelled: L.statusCancelled
    };

    function computeTournamentStatus(regStart, regEnd, dateStart, dateEnd) {
        var now = new Date().toISOString().substring(0, 10);
        if (regStart && now < regStart) return 'upcoming';
        if (regStart && regEnd && now >= regStart && now <= regEnd) return 'registration_open';
        if (dateEnd && now > dateEnd) return 'completed';
        if (dateStart && now >= dateStart) return 'ongoing';
        if (regEnd && now > regEnd) return 'registration_closed';
        return 'upcoming';
    }

    // ---- SVG Icons ----
    var ICONS = {
        grid: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg>',
        users: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 00-3-3.87"/><path d="M16 3.13a4 4 0 010 7.75"/></svg>',
        trophy: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 9H4.5a2.5 2.5 0 010-5C7 4 7 7 7 7"/><path d="M18 9h1.5a2.5 2.5 0 000-5C17 4 17 7 17 7"/><path d="M4 22h16"/><path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20 7 22"/><path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20 17 22"/><path d="M18 2H6v7a6 6 0 1012 0V2z"/></svg>',
        chart: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 20V10"/><path d="M12 20V4"/><path d="M6 20v-6"/></svg>',
        file: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>',
        card: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="1" y="4" width="22" height="16" rx="2" ry="2"/><line x1="1" y1="10" x2="23" y2="10"/></svg>',
        location: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0118 0z"/><circle cx="12" cy="10" r="3"/></svg>',
        coach: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>',
        star: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>',
        wallet: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="1" y="5" width="22" height="16" rx="2"/><path d="M1 10h22"/><circle cx="18" cy="15" r="1"/></svg>',
        ticket: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M2 9a3 3 0 013-3h14a3 3 0 013 3v0a3 3 0 01-3 3v1a3 3 0 013 3v0a3 3 0 01-3 3H5a3 3 0 01-3-3v0a3 3 0 013-3v-1a3 3 0 01-3-3z"/></svg>'
    };

    var SECTION_ICONS = {
        users: '👥',
        tournaments: '🏆',
        players: '📊',
        memberships: '💳',
        courts: '🏟️',
        coaches: '🎓',
        ratings: '⭐',
        payments: '💰',
        vouchers: '🎫'
    };


    var ROLE_SECTIONS = {
        admin:   ['dashboard', 'content', 'tournaments', 'players', 'courts', 'coaches', 'ratings', 'users', 'memberships', 'payments', 'vouchers'],
        manager: ['dashboard', 'content', 'tournaments', 'players', 'courts', 'coaches', 'ratings', 'users', 'memberships', 'payments', 'vouchers']
    };

    // ---- Initialize namespace ----
    window.KSLT_ADMIN = {
        isEn: isEn,
        L: L,
        ICONS: ICONS,
        SECTION_ICONS: SECTION_ICONS,
        CATEGORIES: CATEGORIES,
        TOURNAMENT_FORMATS: TOURNAMENT_FORMATS,
        TOURNAMENT_STATUSES: TOURNAMENT_STATUSES,
        COURT_TYPES: COURT_TYPES,
        COURT_SURFACES: COURT_SURFACES,
        COURT_AMENITIES: COURT_AMENITIES,
        ROLE_SECTIONS: ROLE_SECTIONS,
        computeTournamentStatus: computeTournamentStatus,
        cachedCategories: cachedCategories,
        categoriesMap: categoriesMap,
        client: null,
        currentRole: 'manager',
        currentUserId: null
    };

    // loadCategories must update KSLT_ADMIN properties directly
    window.KSLT_ADMIN.loadCategories = async function() {
        var A = window.KSLT_ADMIN;
        if (A.cachedCategories.length > 0) return;
        if (!A.client) return;
        var result = await A.client.from('categories').select('*').order('sort_order', { ascending: true });
        var data = result.data || [];
        // Clear and push (keep reference)
        A.cachedCategories.length = 0;
        for (var i = 0; i < data.length; i++) {
            A.cachedCategories.push(data[i]);
            A.categoriesMap[data[i].id] = data[i];
        }
    };

})();
