-- ============================================
-- Рейтинг NTRP из списков клуба
-- ============================================
--
-- Собрано скриптом import/build-ntrp-sql.py — правки вносить туда,
-- иначе они потеряются при следующей сборке.
--
-- Из двух рейтингов берём одиночный: парный клуб отменил.
-- Категорию не трогаем — она придёт отдельным списком.

BEGIN;

-- 1. Рейтинг тем, кто уже заведён (призёры из новостей)
UPDATE players SET ntrp_rating = 5.5 WHERE id = 'atham-israilov';
UPDATE players SET ntrp_rating = 5.0 WHERE id = 'erlan-shekerbekov';
UPDATE players SET ntrp_rating = 5.0 WHERE id = 'aziz-bazakov';
UPDATE players SET ntrp_rating = 5.0 WHERE id = 'roman-dolgushin';
UPDATE players SET ntrp_rating = 4.5 WHERE id = 'arsen-umurzakov';
UPDATE players SET ntrp_rating = 4.5 WHERE id = 'kirill-leontev';
UPDATE players SET ntrp_rating = 4.25 WHERE id = 'ruslan-kuldzhaev';
UPDATE players SET ntrp_rating = 4.25 WHERE id = 'azim-isakov';
UPDATE players SET ntrp_rating = 4.0 WHERE id = 'furkat-sadykov';
UPDATE players SET ntrp_rating = 4.0 WHERE id = 'rashid-seyitov';
UPDATE players SET ntrp_rating = 4.0 WHERE id = 'ramil-miftahutdinov';
UPDATE players SET ntrp_rating = 4.0 WHERE id = 'ulugbek-salymbekov';
UPDATE players SET ntrp_rating = 4.0 WHERE id = 'ilya-velikorodnyy';
UPDATE players SET ntrp_rating = 4.0 WHERE id = 'bakyt-kayypov';
UPDATE players SET ntrp_rating = 4.0 WHERE id = 'azamat-dzhumabaev';
UPDATE players SET ntrp_rating = 4.0 WHERE id = 'erbol-kylychev';
UPDATE players SET ntrp_rating = 3.5 WHERE id = 'kanat-abdrahmanov';
UPDATE players SET ntrp_rating = 3.7 WHERE id = 'aleksandr-fomin';
UPDATE players SET ntrp_rating = 3.7 WHERE id = 'zakir-nazarov';
UPDATE players SET ntrp_rating = 3.7 WHERE id = 'vladislav-kim';
UPDATE players SET ntrp_rating = 3.7 WHERE id = 'hamit-karaketov';
UPDATE players SET ntrp_rating = 3.7 WHERE id = 'erlan-sydykov';
UPDATE players SET ntrp_rating = 3.7 WHERE id = 'iskender-kurmanov';
UPDATE players SET ntrp_rating = 3.5 WHERE id = 'abdikiim-mahmutov';
UPDATE players SET ntrp_rating = 3.5 WHERE id = 'ivan-korabelnikov';
UPDATE players SET ntrp_rating = 3.5 WHERE id = 'temirbek-musaev';
UPDATE players SET ntrp_rating = 3.5 WHERE id = 'alymbek-orokov';
UPDATE players SET ntrp_rating = 3.5 WHERE id = 'sardar-umarov';
UPDATE players SET ntrp_rating = 3.5 WHERE id = 'iskender-seydimatov';
UPDATE players SET ntrp_rating = 3.0 WHERE id = 'taalay-esenamanov';
UPDATE players SET ntrp_rating = 3.0 WHERE id = 'alan-adzhibekov';
UPDATE players SET ntrp_rating = 3.0 WHERE id = 'zamir-borubaev';
UPDATE players SET ntrp_rating = 3.0 WHERE id = 'argen-shakidiev';
UPDATE players SET ntrp_rating = 3.0 WHERE id = 'amir-bazhanov';
UPDATE players SET ntrp_rating = 3.0 WHERE id = 'eldiyar-boruev';
UPDATE players SET ntrp_rating = 3.0 WHERE id = 'zhanat-kydraliev';
UPDATE players SET ntrp_rating = 2.5 WHERE id = 'azat-sakebaev';
UPDATE players SET ntrp_rating = 2.0 WHERE id = 'adil-valimamedov';
UPDATE players SET ntrp_rating = 4.0 WHERE id = 'anastasiya-trofimushkina';
UPDATE players SET ntrp_rating = 4.0 WHERE id = 'roza-isabekova';
UPDATE players SET ntrp_rating = 4.0 WHERE id = 'aysuluu-chokoeva';
UPDATE players SET ntrp_rating = 4.0 WHERE id = 'asel-makaeva';
UPDATE players SET ntrp_rating = 4.0 WHERE id = 'tat-yana-nechaeva';
UPDATE players SET ntrp_rating = 4.0 WHERE id = 'gulmira-orozalieva';
UPDATE players SET ntrp_rating = 4.0 WHERE id = 'ayday-orozbaeva';
UPDATE players SET ntrp_rating = 3.5 WHERE id = 'barno-tursunova';
UPDATE players SET ntrp_rating = 3.5 WHERE id = 'anastasiya-adzhibekova';
UPDATE players SET ntrp_rating = 3.5 WHERE id = 'adel-dzhayloeva';
UPDATE players SET ntrp_rating = 3.5 WHERE id = 'valeriya-pak';
UPDATE players SET ntrp_rating = 3.0 WHERE id = 'zulayka-talasbek-kyzy';
UPDATE players SET ntrp_rating = 3.0 WHERE id = 'nataliya-tsurban';
UPDATE players SET ntrp_rating = 3.0 WHERE id = 'kalima-askarova';
UPDATE players SET ntrp_rating = 3.0 WHERE id = 'zarima-baygubatova';
UPDATE players SET ntrp_rating = 3.0 WHERE id = 'akzholtoy-isabekova';
UPDATE players SET ntrp_rating = 2.5 WHERE id = 'aygerim-alizhanova';
UPDATE players SET ntrp_rating = 2.5 WHERE id = 'burul-rakisheva';
UPDATE players SET ntrp_rating = 2.5 WHERE id = 'ayzhan-temiralieva';
UPDATE players SET ntrp_rating = 2.5 WHERE id = 'shoola-baysaeva';
UPDATE players SET ntrp_rating = 2.5 WHERE id = 'tatyana-mashenskaya';
UPDATE players SET ntrp_rating = 2.5 WHERE id = 'yana-eresko';
UPDATE players SET ntrp_rating = 2.5 WHERE id = 'narmina-ahmatova';
UPDATE players SET ntrp_rating = 2.5 WHERE id = 'aziza-musaeva';
UPDATE players SET ntrp_rating = 2.5 WHERE id = 'asel-ashimova';

-- 2. Остальные участники и члены клуба
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('anton-sevalnev', 'Антон Севальнев', 'men', 'futures', 5.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aleksandr-logvinenko', 'Александр Логвиненко', 'men', 'futures', 5.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('rufat-mirdzhaliev', 'Руфат Мирджалиев', 'men', 'futures', 5.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('eldar-safiullin', 'Эльдар Сафиуллин', 'men', 'futures', 5.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('nikita-boykov', 'Никита Бойков', 'men', 'futures', 4.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('baturhan-usenov', 'Батурхан Усенов', 'men', 'futures', 4.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('ermek-aratov', 'Эрмек Аратов', 'men', 'futures', 5.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('mihail-chertkov', 'Михаил Чертков', 'men', 'futures', 4.25, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('ilan-aatabaev', 'Илан Аатабаев', 'men', 'futures', 4.25, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('igor-muratov', 'Игорь Муратов', 'men', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('konstantin-lazarev', 'Константин Лазарев', 'men', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('avtandil-ernest', 'Автандил Эрнэст', 'men', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('roman-gudi', 'Роман Гуди', 'men', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('rustam-faizov', 'Рустам Фаизов', 'men', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('daniyar-atahanov', 'Данияр Атаханов', 'men', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('azis-myrzaev', 'Азис Мырзаев', 'men', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('anvar-askarov', 'Анвар Аскаров', 'men', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('sergey-sokolov', 'Сергей Соколов', 'men', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('almazbek-emilkanov', 'Алмазбек Эмильканов', 'men', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('evgeniy-tsoy', 'Евгений Цой', 'men', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('rustam-suleymanov', 'Рустам Сулейманов', 'men', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('ravil-miftahutdinov', 'Равиль Мифтахутдинов', 'men', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('daniel-gubler', 'Даниэль Гублер', 'men', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('dmitriy-bondarev', 'Дмитрий Бондарев', 'men', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('dastan-omuraliev', 'Дастан Омуралиев', 'men', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('ravil-rahmatulin', 'Равиль Рахматулин', 'men', 'futures', 3.7, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('ernest-takirov', 'Эрнест Такиров', 'men', 'futures', 3.7, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('arslan-dzhoroev', 'Арслан Джороев', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('seytek-chalbaev', 'Сейтек Чалбаев', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('hanganu-igor', 'Хангану Игорь', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('ulukbek-bekbosunov', 'Улукбек Бекбосунов', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('farruh-mavlitov', 'Фаррух Мавлитов', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('avanes-balyan', 'Аванес Балян', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('erkin-isakov', 'Эркин Исаков', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('vitaliy-kachala', 'Виталий Качала', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('andrey-lebedev', 'Андрей Лебедев', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('abdurahman-niyazov', 'Абдурахман Ниязов', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('syngyz-ismatov', 'Сынгыз Исматов', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aybek-zholdoshbekov', 'Айбек Жолдошбеков', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('edil-dzhanybekov', 'Эдиль Джаныбеков', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('danil-bondar', 'Данил Бондарь', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('yan-skazka', 'Ян Сказка', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('kadyrbek-adiev', 'Кадырбек Адиев', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('etan-patek', 'Этан Патэк', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('denis-ens', 'Денис Энс', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('denis-li', 'Денис Ли', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('zakir-gudadzhanov', 'Закир Гудаджанов', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('evgeniy-karanskiy', 'Евгений Каранский', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('ermamat-matosmonov', 'Эрмамат Матосмонов', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('murat-noruzbaev', 'Мурат Норузбаев', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('esen-azimov', 'Эсен Азимов', 'men', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('stanislav-danilevich', 'Станислав Данилевич', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('dilshat-bazhanov', 'Дильшат Бажанов', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('kamil-yakupov', 'Камиль Якупов', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('yaroslav-mironov', 'Ярослав Миронов', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('kerimbaev-erkin', 'Керимбаев Эркин', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('sanzhar-masadykov', 'Санжар Масадыков', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('nurlan-azygaliev', 'Нурлан Азыгалиев', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('meder-abakirov', 'Медер Абакиров', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('kamil-atykanov', 'Камиль Атыканов', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('mirlan-kubatov', 'Мирлан Кубатов', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aleksandr-dyachenko', 'Александр Дьяченко', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('azat-bazarkulov', 'Азат Базаркулов', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('vitaliy-valyaev', 'Виталий Валяев', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('murat-alaychyev', 'Мурат Алайчыев', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('azamat-araev', 'Азамат Араев', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('ilyas-dadybaev', 'Ильяс Дадыбаев', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aziz-burhanov', 'Азиз Бурханов', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('kirill-vays', 'Кирилл Вайс', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('ilzat-husainov', 'Ильзат Хусаинов', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('stanislav-shumilin', 'Станислав Шумилин', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('leonid-tsoy', 'Леонид Цой', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('dmitriy-diskin', 'Дмитрий Дискин', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('ermek-abakirov', 'Эрмек Абакиров', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('sergey-levin', 'Сергей Левин', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('chingis-chukin', 'Чингис Чукин', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('temirlan-mirgazy', 'Темирлан Миргазы', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('mirlan-usenkanov', 'Мирлан Усенканов', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('akylbek-tentiev', 'Акылбек Тентиев', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('vlad-afonin', 'Влад Афонин', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('denis-renner', 'Денис Реннер', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('azat-mukaev', 'Азат Мукаев', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('askar-zhumagulov', 'Аскар Жумагулов', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('azamat-nurdinov', 'Азамат Нурдинов', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('nurbek-nurbekov', 'Нурбек Нурбеков', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('amir-kanaev', 'Амир Канаев', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('dmitriy-dudrin', 'Дмитрий Дудрин', 'men', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('ivan-shvyrov', 'Иван Швыров', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('shavkat-mihmanov', 'Шавкат Михманов', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('igor-kan', 'Игорь Кан', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aman-kanaev', 'Аман Канаев', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('sardar-artykbaev', 'Сардар Артыкбаев', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('adilet-aytiev', 'Адилет Айтиев', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('bekzat-imenov', 'Бекзат Именов', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('vladislav-abrosimov', 'Владислав Абросимов', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('faruh-suleymanov', 'Фарух Сулейманов', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aleksey-pyankov', 'Алексей Пьянков', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('atay-begaliev', 'Атай Бегалиев', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('azat-musaev', 'Азат Мусаев', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('konstantin-kim', 'Константин Ким', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('nur-tulebaev', 'Нур Тулебаев', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('dmitriy-pak', 'Дмитрий Пак', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('sanzhar-ergeshaliev', 'Санжар Эргешалиев', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('dzhantay-otorbaev', 'Джантай Оторбаев', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('elnur-omurzakov', 'Элнур Омурзаков', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('allayar-nasyrov', 'Аллаяр Насыров', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('dilshat-nurdinov', 'Дильшат Нурдинов', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('sultan-ibragimov', 'Султан Ибрагимов', 'men', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('nurmamat-uulu-bekmamat', 'Нурмамат уулу Бекмамат', 'men', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('rustam-ushur', 'Рустам Ушур', 'men', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('askar-abaskanov', 'Аскар Абасканов', 'men', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('yaroslav-bredihin', 'Ярослав Бредихин', 'men', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('bekzhan-kylychbekov', 'Бекжан Кылычбеков', 'men', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('ahmedzhan-adzhuev', 'Ахмеджан Аджуев', 'men', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('nikita-potrimaylo', 'Никита Потримайло', 'men', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('bahram-mambetov', 'Бахрам Мамбетов', 'men', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('timur-uzagaliev', 'Тимур Узагалиев', 'men', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('denis-asanov', 'Денис Асанов', 'men', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aleksandr-kim', 'Александр Ким', 'men', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('imar-kamalov', 'Имар Камалов', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('nurmat-sakebaev', 'Нурмат Сакебаев', 'men', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('tilegen-mamyrkaliev', 'Тилеген Мамыркалиев', 'men', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('iskender-kadyrov', 'Искендер Кадыров', 'men', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('nelli-buyuklyanova', 'Нелли Буюклянова', 'women', 'futures', NULL, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('arina-belyaeva', 'Арина Беляева', 'women', 'futures', NULL, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('sofya-blagovisnaya', 'Софья Благовисная', 'women', 'futures', 4.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('leyli-blagovisnaya', 'Лейли Благовисная', 'women', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('natalya-klimenko', 'Наталья Клименко', 'women', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('shirin-karimova', 'Ширин Каримова', 'women', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('marianna-proskurina', 'Марианна Проскурина', 'women', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('yana-belekova', 'Яна Белекова', 'women', 'futures', 4.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('valeriya-hegay', 'Валерия Хегай', 'women', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('elena-kan', 'Елена Кан', 'women', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('liliya-rahmatulina', 'Лилия Рахматулина', 'women', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('tatyana-andreevskaya', 'Татьяна Андреевская', 'women', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('asel-isabekova', 'Асель Исабекова', 'women', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('ekateria-titova', 'Екатериа Титова', 'women', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('natalya-temirbaeva', 'Наталья Темирбаева', 'women', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('elizaveta-aleksandra-ponomareva', 'Елизавета-Александра Пономарева', 'women', 'futures', 3.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aleksandra-muchkina', 'Александра Мучкина', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('nazgul-kerimalieva', 'Назгуль Керималиева', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aydana-aktanova', 'Айдана Актанова', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aysuluu-orokova', 'Айсулуу Орокова', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('amina-kurbanova', 'Амина Курбанова', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('malika-shamil', 'Малика Шамиль', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('altynay-omuralieva', 'Алтынай Омуралиева', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('akzholtoy-bolotbekova', 'Акжолтой Болотбекова', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('keremet-begmatova', 'Керемет Бегматова', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('bermet-samsalieva', 'Бермет Самсалиева', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('mariya-gurina', 'Мария Гурина', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('kalicha-taygurova', 'Калича Тайгурова', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('elizaveta-pilipenko', 'Елизавета Пилипенко', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aygerim-sarieva', 'Айгерим Сариева', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('darya-zinina', 'Дарья Зинина', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('sveta-poharel', 'Света Похарел', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('olga-petrovskaya', 'Ольга Петровская', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('meerim-zhumabekova', 'Мээрим Жумабекова', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('natalya-seytmuratova', 'Наталья Сейтмуратова', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('svetlana-hanazhenko', 'Светлана Ханаженко', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('adelya-kamchybekova', 'Аделя Камчыбекова', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('nella-kotelnikova', 'Нэлла Котельникова', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aydina-aytmatova', 'Айдина Айтматова', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('asel-abdygulova', 'Асель Абдыгулова', 'women', 'futures', 3.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aychurok-marat-kyzy', 'Айчурок Марат кызы', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('ayday-stalbekova', 'Айдай Сталбекова', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('kasiet-samsalieva', 'Касиет Самсалиева', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('saliya-ustemirova', 'Салия Устемирова', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('asel-orokova', 'Асель Орокова', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('amal-brenneman', 'Амаль Бреннеман', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('madina-kadyrova', 'Мадина Кадырова', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('diana-esenbekova', 'Диана Эсенбекова', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aleksandra-panfilova', 'Александра Панфилова', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aida-nogoybaeva', 'Аида Ногойбаева', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aliya-abaskanova', 'Алия Абасканова', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('nurzhamal-dzhanibekova', 'Нуржамал Джанибекова', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('kyzzhibek-batyrkanova', 'Кызжибек Батырканова', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('ayzana-toguzbaeva', 'Айзана Тогузбаева', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('zuhra-muralieva', 'Зухра Муралиева', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('deniz-rahmatova', 'Дениз Рахматова', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('diana-imanahunova', 'Диана Иманахунова', 'women', 'futures', 2.5, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aysuluu-erkulova', 'Айсулуу Эркулова', 'women', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('cholpon-narbaeva', 'Чолпон Нарбаева', 'women', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('feyruza-ikram', 'Фейруза Икрам', 'women', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('nargiza-sakebaeva', 'Наргиза Сакебаева', 'women', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aysha-turdumambetova', 'Айша Турдумамбетова', 'women', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('elina-samanova', 'Элина Саманова', 'women', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aisha-nurbekova', 'Аиша Нурбекова', 'women', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aykanysh-tabaldyeva', 'Айканыш Табалдыева', 'women', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('aziza-samratova', 'Азиза Самратова', 'women', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('ekaterina-shumilina', 'Екатерина Шумилина', 'women', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('vasilya-iskendirova', 'Василя Искендирова', 'women', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('albina-isabekova', 'Альбина Исабекова', 'women', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, name, gender, category_id, ntrp_rating, points, wins, losses) VALUES ('altynay-dzhamanbaeva', 'Алтынай Джаманбаева', 'women', 'futures', 2.0, 0, 0, 0) ON CONFLICT (id) DO NOTHING;

-- 3. Что получилось
SELECT gender AS пол, COUNT(*) AS игроков,
       COUNT(ntrp_rating) AS с_рейтингом,
       ROUND(AVG(ntrp_rating)::numeric, 2) AS средний
FROM players GROUP BY gender ORDER BY gender;

COMMIT;
