-- ============================================
-- Турниры и призёры из новостей
-- ============================================
--
-- Собрано скриптом import/build-tournaments-from-news.py — правки
-- вносить туда, иначе они потеряются при следующей сборке.
--
-- Очки не начисляем: points_earned = 0. Рейтинг клуб перенесёт
-- отдельно, а карточки игроков сведутся с учётными записями, когда
-- люди начнут регистрироваться.
--
-- Игроки заводятся именем и полом: больше в новостях ничего нет.

BEGIN;

-- 0. Прошлая заливка, если была. У части турниров адреса совпадали,
--    и призёры женского и мужского разрядов слиплись в один
--    пьедестал — такие записи надо переписать начисто.
--    В таблице только турниры из новостей, чужого здесь нет.
DELETE FROM tournament_results;
DELETE FROM tournaments;

-- 1. Игроки-призёры (уже заведённых пропускаем)

-- 2. Турниры
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('mezhdunarodnyy-prazdnik-tennisa-kia-open-2023-master-20250427', 'Международный праздник тенниса KIA OPEN - 2023! — Masters, микст', 'masters', 'mixed', 'mixed_doubles', 'completed', '2025-04-27', '2025-04-27', NULL, NULL, 74, '2025-04-27 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('mezhdunarodnyy-prazdnik-tennisa-kia-open-2023-future-20250427', 'Международный праздник тенниса KIA OPEN - 2023! — Futures, парный, мужской', 'futures', 'men', 'doubles', 'completed', '2025-04-27', '2025-04-27', NULL, NULL, 74, '2025-04-27 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('mega-cup-2026-futures-parnyy-20260125', 'MEGA CUP — 2026 — Futures, парный', 'futures', 'mixed', 'doubles', 'completed', '2026-01-25', '2026-01-25', NULL, 't-club', 6, '2026-01-25 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('mega-cup-2026-masters-parnyy-20260125', 'MEGA CUP — 2026 — Masters, парный', 'masters', 'mixed', 'doubles', 'completed', '2026-01-25', '2026-01-25', NULL, 't-club', 6, '2026-01-25 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('night-friends-cup-20260228', 'NIGHT FRIENDS'' CUP', 'friendly', 'mixed', 'doubles', 'completed', '2026-02-28', '2026-02-28', NULL, 'tay-breyk', 6, '2026-02-28 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('lady-s-cup-futures-parnyy-zhenskiy-20260315', 'LADY’S CUP — Futures, парный, женский', 'futures', 'women', 'doubles', 'completed', '2026-03-15', '2026-03-15', NULL, 't-club', 4, '2026-03-15 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('lady-s-cup-masters-parnyy-zhenskiy-20260315', 'LADY’S CUP — Masters, парный, женский', 'masters', 'women', 'doubles', 'completed', '2026-03-15', '2026-03-15', NULL, 't-club', 4, '2026-03-15 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('friends-cup-2026-tour-parnyy-zhenskiy-20260413', 'FRIENDS’ CUP 2026 — Tour, парный, женский', 'tour', 'women', 'doubles', 'completed', '2026-04-13', '2026-04-13', NULL, 't-club', 4, '2026-04-13 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('friends-cup-2026-futures-parnyy-zhenskiy-20260413', 'FRIENDS’ CUP 2026 — Futures, парный, женский', 'futures', 'women', 'doubles', 'completed', '2026-04-13', '2026-04-13', NULL, 't-club', 4, '2026-04-13 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('friends-cup-2026-masters-parnyy-20260413', 'FRIENDS’ CUP 2026 — Masters, парный', 'masters', 'men', 'doubles', 'completed', '2026-04-13', '2026-04-13', NULL, 't-club', 4, '2026-04-13 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('friends-cup-2026-tour-parnyy-20260413', 'FRIENDS’ CUP 2026 — Tour, парный', 'tour', 'men', 'doubles', 'completed', '2026-04-13', '2026-04-13', NULL, 't-club', 4, '2026-04-13 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('mayskiy-chempionat-kslt-itogi-futures-odinochnyy-muz-20260510', 'МАЙСКИЙ ЧЕМПИОНАТ КСЛТ — ИТОГИ — Futures, одиночный, мужской', 'futures', 'men', 'singles', 'completed', '2026-05-10', '2026-05-10', NULL, 'kapriz-issyk-kul-resort-hotel', 3, '2026-05-10 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('mayskiy-chempionat-kslt-itogi-masters-odinochnyy-muz-20260510', 'МАЙСКИЙ ЧЕМПИОНАТ КСЛТ — ИТОГИ — Masters, одиночный, мужской', 'masters', 'men', 'singles', 'completed', '2026-05-10', '2026-05-10', NULL, 'kapriz-issyk-kul-resort-hotel', 3, '2026-05-10 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('mayskiy-chempionat-kslt-itogi-tour-odinochnyy-muzhsk-20260510', 'МАЙСКИЙ ЧЕМПИОНАТ КСЛТ — ИТОГИ — Tour, одиночный, мужской', 'tour', 'men', 'singles', 'completed', '2026-05-10', '2026-05-10', NULL, 'kapriz-issyk-kul-resort-hotel', 3, '2026-05-10 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('mayskiy-chempionat-kslt-itogi-futures-parnyy-muzhsko-20260510', 'МАЙСКИЙ ЧЕМПИОНАТ КСЛТ — ИТОГИ — Futures, парный, мужской', 'futures', 'men', 'doubles', 'completed', '2026-05-10', '2026-05-10', NULL, 'kapriz-issyk-kul-resort-hotel', 4, '2026-05-10 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('mayskiy-chempionat-kslt-itogi-masters-parnyy-muzhsko-20260510', 'МАЙСКИЙ ЧЕМПИОНАТ КСЛТ — ИТОГИ — Masters, парный, мужской', 'masters', 'men', 'doubles', 'completed', '2026-05-10', '2026-05-10', NULL, 'kapriz-issyk-kul-resort-hotel', 4, '2026-05-10 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('mayskiy-chempionat-kslt-itogi-tour-parnyy-zhenskiy-20260510', 'МАЙСКИЙ ЧЕМПИОНАТ КСЛТ — ИТОГИ — Tour, парный, женский', 'tour', 'women', 'doubles', 'completed', '2026-05-10', '2026-05-10', NULL, 'kapriz-issyk-kul-resort-hotel', 4, '2026-05-10 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('mayskiy-chempionat-kslt-itogi-futures-parnyy-zhenski-20260510', 'МАЙСКИЙ ЧЕМПИОНАТ КСЛТ — ИТОГИ — Futures, парный, женский', 'futures', 'women', 'doubles', 'completed', '2026-05-10', '2026-05-10', NULL, 'kapriz-issyk-kul-resort-hotel', 4, '2026-05-10 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('reytingovye-turniry-kslt-zhenskiy-odinochnyy-futures-20260516', 'РЕЙТИНГОВЫЕ ТУРНИРЫ КСЛТ — ЖЕНСКИЙ ОДИНОЧНЫЙ FUTURES И TOUR', 'futures', 'women', 'singles', 'completed', '2026-05-16', '2026-05-16', NULL, 'tay-breyk', 3, '2026-05-16 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('reytingovyy-turnir-futures-tay-breyk-20260517', 'РЕЙТИНГОВЫЙ ТУРНИР FUTURES — ТАЙ-БРЕЙК', 'futures', 'men', 'singles', 'completed', '2026-05-17', '2026-05-17', NULL, 'tay-breyk', 3, '2026-05-17 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('druzheskiy-parnyy-turnir-tay-breyk-27-maya-zhenskiy-20260527', 'ДРУЖЕСКИЙ ПАРНЫЙ ТУРНИР — ТАЙ-БРЕЙК, 27 МАЯ — женский', 'friendly', 'women', 'doubles', 'completed', '2026-05-27', '2026-05-27', NULL, 'tay-breyk', 4, '2026-05-27 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('druzheskiy-parnyy-turnir-tay-breyk-27-maya-muzhskoy-20260527', 'ДРУЖЕСКИЙ ПАРНЫЙ ТУРНИР — ТАЙ-БРЕЙК, 27 МАЯ — мужской', 'friendly', 'men', 'doubles', 'completed', '2026-05-27', '2026-05-27', NULL, 'tay-breyk', 6, '2026-05-27 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('booblik-open-2026-futures-parnyy-zhenskiy-20260614', 'BOOBLIK OPEN 2026 — Futures, парный, женский', 'futures', 'women', 'doubles', 'completed', '2026-06-14', '2026-06-14', NULL, 'tay-breyk', 6, '2026-06-14 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('booblik-open-2026-futures-parnyy-muzhskoy-20260614', 'BOOBLIK OPEN 2026 — Futures, парный, мужской', 'futures', 'men', 'doubles', 'completed', '2026-06-14', '2026-06-14', NULL, 'tay-breyk', 6, '2026-06-14 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-20260724', 'SUMMER BREEZE CUP – 2026 — дружеский, парный', 'friendly', 'mixed', 'doubles', 'completed', '2026-07-24', '2026-07-24', NULL, 'kapriz-issyk-kul-resort-hotel', 6, '2026-07-24 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('summer-breeze-cup-2026-druzheskiy-mikst-dopolnitelny-20260724', 'SUMMER BREEZE CUP – 2026 — дружеский, микст, дополнительный', 'friendly', 'mixed', 'mixed_doubles', 'completed', '2026-07-24', '2026-07-24', NULL, 'kapriz-issyk-kul-resort-hotel', 4, '2026-07-24 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-muzhskoy-20260724', 'SUMMER BREEZE CUP – 2026 — дружеский, парный, мужской', 'friendly', 'men', 'doubles', 'completed', '2026-07-24', '2026-07-24', NULL, 'kapriz-issyk-kul-resort-hotel', 6, '2026-07-24 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-muzhskoy-do-20260724', 'SUMMER BREEZE CUP – 2026 — дружеский, парный, мужской, дополнительный', 'friendly', 'men', 'doubles', 'completed', '2026-07-24', '2026-07-24', NULL, 'kapriz-issyk-kul-resort-hotel', 4, '2026-07-24 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('druzheskiy-parnyy-turnir-brk-group-zhenskiy-20260808', 'ДРУЖЕСКИЙ ПАРНЫЙ ТУРНИР — BRK GROUP — женский', 'friendly', 'women', 'doubles', 'completed', '2026-08-08', '2026-08-08', NULL, 'tay-breyk', 6, '2026-08-08 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;
INSERT INTO tournaments (id, title, category_id, gender, format, status, date_start, date_end, image, court_id, max_participants, published_at) VALUES ('druzheskiy-parnyy-turnir-brk-group-muzhskoy-20260808', 'ДРУЖЕСКИЙ ПАРНЫЙ ТУРНИР — BRK GROUP — мужской', 'friendly', 'men', 'doubles', 'completed', '2026-08-08', '2026-08-08', NULL, 'tay-breyk', 6, '2026-08-08 09:00:00+06'::timestamptz) ON CONFLICT (id) DO NOTHING;

-- 3. Пьедесталы. Очки нулевые — начислим, когда перенесём рейтинг
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mezhdunarodnyy-prazdnik-tennisa-kia-open-2023-master-20250427', 'arsen-umurzakov', 'W', 0, 2025) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mezhdunarodnyy-prazdnik-tennisa-kia-open-2023-master-20250427', 'darya-malbekova', 'W', 0, 2025) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mezhdunarodnyy-prazdnik-tennisa-kia-open-2023-master-20250427', 'azamat-dzhumabaev', 'F', 0, 2025) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mezhdunarodnyy-prazdnik-tennisa-kia-open-2023-master-20250427', 'albina-sulaymanova', 'F', 0, 2025) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mezhdunarodnyy-prazdnik-tennisa-kia-open-2023-master-20250427', 'erlan-shekerbekov', '3RD', 0, 2025) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mezhdunarodnyy-prazdnik-tennisa-kia-open-2023-master-20250427', 'larisa-yancharuk', '3RD', 0, 2025) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mezhdunarodnyy-prazdnik-tennisa-kia-open-2023-future-20250427', 'anvar-murtazaev', 'W', 0, 2025) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mezhdunarodnyy-prazdnik-tennisa-kia-open-2023-future-20250427', 'muhtor-asadov', 'W', 0, 2025) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mezhdunarodnyy-prazdnik-tennisa-kia-open-2023-future-20250427', 'abdikiim-mahmutov', 'F', 0, 2025) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mezhdunarodnyy-prazdnik-tennisa-kia-open-2023-future-20250427', 'sergey-pyzhik', 'F', 0, 2025) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mezhdunarodnyy-prazdnik-tennisa-kia-open-2023-future-20250427', 'bolot-davlyatov', '3RD', 0, 2025) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mezhdunarodnyy-prazdnik-tennisa-kia-open-2023-future-20250427', 'shumkar-abdrazak-uulu', '3RD', 0, 2025) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mega-cup-2026-futures-parnyy-20260125', 'hamit-karaketov', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mega-cup-2026-futures-parnyy-20260125', 'zhanat-kydraliev', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mega-cup-2026-futures-parnyy-20260125', 'erbol-kylychev', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mega-cup-2026-futures-parnyy-20260125', 'eldiyar-boruev', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mega-cup-2026-futures-parnyy-20260125', 'azamat-dzhumabaev', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mega-cup-2026-futures-parnyy-20260125', 'aygerim-alizhanova', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mega-cup-2026-masters-parnyy-20260125', 'malik-kamalov', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mega-cup-2026-masters-parnyy-20260125', 'anastasiya-trofimushkina', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mega-cup-2026-masters-parnyy-20260125', 'kirill-leontev', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mega-cup-2026-masters-parnyy-20260125', 'arsen-umurzakov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mega-cup-2026-masters-parnyy-20260125', 'aziz-bazakov', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mega-cup-2026-masters-parnyy-20260125', 'azim-isakov', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('night-friends-cup-20260228', 'anastasiya-trofimushkina', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('night-friends-cup-20260228', 'azim-isakov', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('night-friends-cup-20260228', 'erbol-kylychev', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('night-friends-cup-20260228', 'zakir-nazarov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('night-friends-cup-20260228', 'furkat-sadykov', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('night-friends-cup-20260228', 'sardar-umarov', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('lady-s-cup-futures-parnyy-zhenskiy-20260315', 'aleksandra-elizaveta-ponomareva', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('lady-s-cup-futures-parnyy-zhenskiy-20260315', 'burul-rakisheva', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('lady-s-cup-futures-parnyy-zhenskiy-20260315', 'kalima-askarova', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('lady-s-cup-futures-parnyy-zhenskiy-20260315', 'aziza-musaeva', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('lady-s-cup-masters-parnyy-zhenskiy-20260315', 'roza-isabekova', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('lady-s-cup-masters-parnyy-zhenskiy-20260315', 'sveta-pokarel', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('lady-s-cup-masters-parnyy-zhenskiy-20260315', 'anastasiya-adzhibekova', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('lady-s-cup-masters-parnyy-zhenskiy-20260315', 'adel-dzhayloeva', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('friends-cup-2026-tour-parnyy-zhenskiy-20260413', 'anastasiya-adzhibekova', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('friends-cup-2026-tour-parnyy-zhenskiy-20260413', 'adel-dzhayloeva', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('friends-cup-2026-tour-parnyy-zhenskiy-20260413', 'natalya-timirbaeva', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('friends-cup-2026-tour-parnyy-zhenskiy-20260413', 'ekaterina-titova', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('friends-cup-2026-futures-parnyy-zhenskiy-20260413', 'yana-eresko', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('friends-cup-2026-futures-parnyy-zhenskiy-20260413', 'valeriya-pak', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('friends-cup-2026-futures-parnyy-zhenskiy-20260413', 'akzholtoy-isabekova', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('friends-cup-2026-futures-parnyy-zhenskiy-20260413', 'gulsan-galieva', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('friends-cup-2026-masters-parnyy-20260413', 'ruslan-kuldzhaev', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('friends-cup-2026-masters-parnyy-20260413', 'hamit-karaketov', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('friends-cup-2026-masters-parnyy-20260413', 'azim-isakov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('friends-cup-2026-masters-parnyy-20260413', 'vladislav-kim', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('friends-cup-2026-tour-parnyy-20260413', 'erbol-kylychev', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('friends-cup-2026-tour-parnyy-20260413', 'adil-valimamedov', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('friends-cup-2026-tour-parnyy-20260413', 'furkat-sadykov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('friends-cup-2026-tour-parnyy-20260413', 'ashirali-yusupov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-futures-odinochnyy-muz-20260510', 'taalay-esenamanov', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-futures-odinochnyy-muz-20260510', 'alan-adzhibekov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-futures-odinochnyy-muz-20260510', 'ibragim-koshoybekov', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-masters-odinochnyy-muz-20260510', 'ramil-miftahutdinov', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-masters-odinochnyy-muz-20260510', 'rashid-seyitov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-masters-odinochnyy-muz-20260510', 'ildiyar-murataliev', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-tour-odinochnyy-muzhsk-20260510', 'azamat-dzhumabaev', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-tour-odinochnyy-muzhsk-20260510', 'vladislav-kim', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-tour-odinochnyy-muzhsk-20260510', 'zakir-nazarov', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-futures-parnyy-muzhsko-20260510', 'temirbek-musaev', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-futures-parnyy-muzhsko-20260510', 'aleksandr-fomin', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-futures-parnyy-muzhsko-20260510', 'kanat-abdrahmanov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-futures-parnyy-muzhsko-20260510', 'kayrat-karakeev', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-masters-parnyy-muzhsko-20260510', 'azamat-dzhumabaev', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-masters-parnyy-muzhsko-20260510', 'ruslan-kuldzhaev', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-masters-parnyy-muzhsko-20260510', 'roman-dolgushin', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-masters-parnyy-muzhsko-20260510', 'abdikiim-mahmutov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-tour-parnyy-zhenskiy-20260510', 'barno-tursunova', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-tour-parnyy-zhenskiy-20260510', 'valeriya-pak', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-tour-parnyy-zhenskiy-20260510', 'aysuluu-chokoeva', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-tour-parnyy-zhenskiy-20260510', 'zulayka-talasbek-kyzy', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-futures-parnyy-zhenski-20260510', 'yana-eresko', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-futures-parnyy-zhenski-20260510', 'roza-isabekova', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-futures-parnyy-zhenski-20260510', 'narmina-ahmatova', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('mayskiy-chempionat-kslt-itogi-futures-parnyy-zhenski-20260510', 'tatyana-mashenskaya', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('reytingovye-turniry-kslt-zhenskiy-odinochnyy-futures-20260516', 'zarima-baygubatova', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('reytingovye-turniry-kslt-zhenskiy-odinochnyy-futures-20260516', 'shoola-baysaeva', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('reytingovye-turniry-kslt-zhenskiy-odinochnyy-futures-20260516', 'nurzhamal-dzhanybekova', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('reytingovyy-turnir-futures-tay-breyk-20260517', 'azat-sakebaev', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('reytingovyy-turnir-futures-tay-breyk-20260517', 'mark-garreta-navo', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('reytingovyy-turnir-futures-tay-breyk-20260517', 'aleksandr-gabaguev', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-tay-breyk-27-maya-zhenskiy-20260527', 'ekaterina-titova', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-tay-breyk-27-maya-zhenskiy-20260527', 'asel-makaeva', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-tay-breyk-27-maya-zhenskiy-20260527', 'anastasiya-trofimushkina', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-tay-breyk-27-maya-zhenskiy-20260527', 'gulmira-orozalieva', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-tay-breyk-27-maya-muzhskoy-20260527', 'hamit-karaketov', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-tay-breyk-27-maya-muzhskoy-20260527', 'vladislav-kim', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-tay-breyk-27-maya-muzhskoy-20260527', 'azamat-dzhumabaev', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-tay-breyk-27-maya-muzhskoy-20260527', 'ivan-korabelnikov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-tay-breyk-27-maya-muzhskoy-20260527', 'ilya-velikorodnyy', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-tay-breyk-27-maya-muzhskoy-20260527', 'erlan-sydykov', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('booblik-open-2026-futures-parnyy-zhenskiy-20260614', 'aziza-musaeva', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('booblik-open-2026-futures-parnyy-zhenskiy-20260614', 'zulayka-talasbek-kyzy', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('booblik-open-2026-futures-parnyy-zhenskiy-20260614', 'narmina-ahmatova', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('booblik-open-2026-futures-parnyy-zhenskiy-20260614', 'ayzhan-temiralieva', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('booblik-open-2026-futures-parnyy-zhenskiy-20260614', 'kalima-askarova', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('booblik-open-2026-futures-parnyy-zhenskiy-20260614', 'asel-ashimova', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('booblik-open-2026-futures-parnyy-muzhskoy-20260614', 'vladislav-kim', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('booblik-open-2026-futures-parnyy-muzhskoy-20260614', 'zakir-nazarov', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('booblik-open-2026-futures-parnyy-muzhskoy-20260614', 'daniil-bondar', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('booblik-open-2026-futures-parnyy-muzhskoy-20260614', 'sanzhar-sultanov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('booblik-open-2026-futures-parnyy-muzhskoy-20260614', 'aleksandr-gabaguev', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('booblik-open-2026-futures-parnyy-muzhskoy-20260614', 'argen-shakidiev', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-20260724', 'muhtor-asadov', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-20260724', 'aygerim-alizhanova', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-20260724', 'azim-isakov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-20260724', 'anastasiya-trofimushkina', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-20260724', 'maksim-kan', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-20260724', 'kamila-erhodzhaeva', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-mikst-dopolnitelny-20260724', 'aleksandr-fomin', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-mikst-dopolnitelny-20260724', 'ayday-orozbaeva', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-mikst-dopolnitelny-20260724', 'gleb-ertman', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-mikst-dopolnitelny-20260724', 'anastasiya-ertman', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-muzhskoy-20260724', 'farhat-dostanov', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-muzhskoy-20260724', 'rezvan-kasanov', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-muzhskoy-20260724', 'atham-israilov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-muzhskoy-20260724', 'iskender-seydimatov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-muzhskoy-20260724', 'ulugbek-salymbekov', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-muzhskoy-20260724', 'arsen-umurzakov', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-muzhskoy-do-20260724', 'amir-bazhanov', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-muzhskoy-do-20260724', 'aymen-azygaliev', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-muzhskoy-do-20260724', 'bakyt-kayypov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('summer-breeze-cup-2026-druzheskiy-parnyy-muzhskoy-do-20260724', 'ramil-miftahutdinov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-brk-group-zhenskiy-20260808', 'asel-ashimova', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-brk-group-zhenskiy-20260808', 'zarima-baygubatova', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-brk-group-zhenskiy-20260808', 'kalicha-tayguronova', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-brk-group-zhenskiy-20260808', 'nataliya-tsurban', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-brk-group-zhenskiy-20260808', 'valeriya-pak', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-brk-group-zhenskiy-20260808', 'kalima-askarova', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-brk-group-muzhskoy-20260808', 'aydar-usmanov', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-brk-group-muzhskoy-20260808', 'eldiyar-boruev', 'W', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-brk-group-muzhskoy-20260808', 'iskender-kurmanov', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-brk-group-muzhskoy-20260808', 'zamir-borubaev', 'F', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-brk-group-muzhskoy-20260808', 'kayrat-karakeev', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;
INSERT INTO tournament_results (tournament_id, player_id, round_reached, points_earned, season) VALUES ('druzheskiy-parnyy-turnir-brk-group-muzhskoy-20260808', 'alymbek-orokov', '3RD', 0, 2026) ON CONFLICT (tournament_id, player_id) DO NOTHING;

-- 4. Что получилось
SELECT t.date_start AS дата, t.category_id AS категория, t.format AS разряд,
       t.title AS турнир, COUNT(r.player_id) AS призёров
FROM tournaments t LEFT JOIN tournament_results r ON r.tournament_id = t.id
GROUP BY t.id, t.date_start, t.category_id, t.format, t.title
ORDER BY t.date_start;

COMMIT;
