-- ============================================================
-- NTRP: новый список игроков клуба
-- ============================================================
--
-- Рейтинг NTRP теперь двумя числами: одиночный разряд и парные турниры. До
-- этого в карточке лежало одно общее поле, и различить их было нельзя.
--
-- Список игроков клуба — это и есть список NTRP. Кого в нём нет, тот гость:
-- карточка ему нужна только чтобы стоять в сетке, своей страницы у него не
-- будет и в рейтинге он не появится. Гости, которые ни разу не играли,
-- удаляются вовсе.
--
-- Источник: «Мужской список NTRP.xlsx» и «Рейтинг жен NTRP_Кыргызстан.xlsx».
-- Имена сверены с карточками; девять расхождений в написании разобраны
-- вручную и подтверждены Costa.
--
-- Что делает файл:
--   1. добавляет поля ntrp_singles, ntrp_doubles и признак гостя;
--   2. проставляет рейтинги 286 игрокам, которые нашлись по имени;
--   3. заводит 61 новых карточек из списка;
--   4. помечает гостями всех, кого в списке нет;
--   5. удаляет тех гостей, за которыми не тянется ни матча, ни заявки, ни
--      привязанного аккаунта — они никому не нужны.
--
-- Запускать можно повторно.

BEGIN;

-- ---- 1. Поля ----

ALTER TABLE public.players
    ADD COLUMN IF NOT EXISTS ntrp_singles numeric (3,2),
    ADD COLUMN IF NOT EXISTS ntrp_doubles numeric (3,2),
    ADD COLUMN IF NOT EXISTS is_guest boolean NOT NULL DEFAULT false;

COMMENT
ON COLUMN public.players.ntrp_singles IS 'NTRP в одиночном разряде';
COMMENT
ON COLUMN public.players.ntrp_doubles IS 'NTRP в парных турнирах';
COMMENT
ON COLUMN public.players.is_guest IS
    'Гость: в списке NTRP его нет. Имя видно в сетке и истории, страницы и места в рейтинге у него нет.';

-- ---- 2. Рейтинги тем, кто в списке ----

UPDATE players p
SET ntrp_singles = н.од,
    ntrp_doubles = н.пар,
    is_guest     = false FROM (VALUES
    ('atham-israilov', 5.25, 5.25),
    ('anton-sevalnev', 5.0, 5.0),
    ('aleksandr-logvinenko', 5.0, 5.0),
    ('erlan-shekerbekov', 5.0, 5.0),
    ('aziz-bazakov', 5.0, 5.0),
    ('rufat-mirdzhaliev', 5.0, 5.0),
    ('eldar-safiullin', 5.0, 5.0),
    ('roman-dolgushin', 5.0, 5.0),
    ('ruslan-kuldzhaev', 5.0, 5.0),
    ('ermek-aratov', 5.0, 5.0),
    ('karim-imanhodzhaev', 5.0, 5.0),
    ('aymen-azygaliev', 5.0, 5.0),
    ('tengiz-atahanov', 4.5, 4.5),
    ('arsen-umurzakov', 4.5, 4.5),
    ('nikita-boykov', 4.5, 4.5),
    ('baturhan-usenov', 4.5, 4.5),
    ('kirill-leontev', 4.5, 5.0),
    ('ruslan-andreev', 4.5, 4.5),
    ('mirdias-tumenbaev', 4.5, 4.5),
    ('kamil-murakov', 4.5, 4.5),
    ('ildiyar-murataliev', 4.5, 4.5),
    ('ilan-aatabaev', 4.5, 4.25),
    ('mihail-chertkov', 4.25, 4.5),
    ('azim-isakov', 4.25, 4.5),
    ('furkat-sadykov', 4.0, 4.25),
    ('rashid-seyitov', 4.0, 4.25),
    ('ramil-miftahutdinov', 4.0, 4.25),
    ('igor-muratov', 4.0, 4.25),
    ('konstantin-lazarev', 4.0, 4.0),
    ('avtandil-ernest', 4.0, 4.0),
    ('roman-gudi', 4.0, 4.0),
    ('rustam-faizov', 4.0, 4.0),
    ('ulugbek-salymbekov', 4.0, 4.25),
    ('daniyar-atahanov', 4.0, 4.0),
    ('azis-myrzaev', 4.0, 4.0),
    ('ilya-velikorodnyy', 4.0, 4.0),
    ('anvar-askarov', 4.0, 4.0),
    ('sergey-sokolov', 4.0, 4.0),
    ('bakyt-kayypov', 4.0, 4.0),
    ('azamat-dzhumabaev', 4.0, 4.25),
    ('almazbek-emilkanov', 4.0, 4.0),
    ('evgeniy-tsoy', 4.0, 4.0),
    ('ravil-miftahutdinov', 4.0, 4.0),
    ('daniel-gubler', 4.0, 4.0),
    ('erbol-kylychev', 4.0, 4.0),
    ('dmitriy-bondarev', 4.0, 4.0),
    ('yura-yun', 4.0, 4.0),
    ('zakir-nazarov', 4.0, 3.7),
    ('hamit-karaketov', 4.0, 3.7),
    ('dastan-omuraliev', 4.0, 3.5),
    ('ravil-rahmatulin', 4.0, 3.5),
    ('rustam-suleymanov', 3.7, 3.7),
    ('aleksandr-fomin', 3.7, 3.7),
    ('vladislav-kim', 3.7, 3.7),
    ('erlan-sydykov', 3.7, 3.7),
    ('ernest-takirov', 3.7, 3.7),
    ('aydar-usmanov', 3.7, 3.7),
    ('alymbek-orokov', 3.7, 3.7),
    ('esen-azimov', 3.7, 3.7),
    ('iskender-kurmanov', 3.7, 3.5),
    ('kadyrbek-adiev', 3.7, 3.5),
    ('zakir-gudadzhanov', 3.7, 3.5),
    ('amir-bazhanov', 3.7, 3.5),
    ('eldiyar-boruev', 3.7, 3.5),
    ('kanat-abdrahmanov', 3.5, 3.7),
    ('kayrat-karakeev', 3.5, 3.5),
    ('arslan-dzhoroev', 3.5, 3.5),
    ('sabyrbek-esenbekov', 3.5, 3.5),
    ('seytek-chalbaev', 3.5, 3.5),
    ('igor-hanganu', 3.5, 3.5),
    ('ulukbek-bekbosunov', 3.5, 3.5),
    ('abdikiim-mahmutov', 3.5, 3.5),
    ('farruh-mavlitov', 3.5, 3.5),
    ('avanes-balyan', 3.5, 3.5),
    ('erkin-isakov', 3.5, 3.5),
    ('vitaliy-kachala', 3.5, 3.5),
    ('andrey-lebedev', 3.5, 3.5),
    ('ivan-korabelnikov', 3.5, 3.7),
    ('syngyz-ismatov', 3.5, 3.5),
    ('aybek-zholdoshbekov', 3.5, 3.7),
    ('edil-dzhanybekov', 3.5, 3.5),
    ('temirbek-musaev', 3.5, 3.5),
    ('kamil-atykanov', 3.5, 3.5),
    ('danil-bondar', 3.5, 3.5),
    ('yan-skazka', 3.5, 3.5),
    ('etan-patek', 3.5, 3.5),
    ('denis-ens', 3.5, 3.5),
    ('denis-li', 3.5, 3.5),
    ('sardar-umarov', 3.5, 3.5),
    ('ermamat-matosmonov', 3.5, 3.5),
    ('iskender-seydimatov', 3.5, 3.5),
    ('murat-noruzbaev', 3.5, 3.5),
    ('kerimbaev-erkin', 3.5, 3.5),
    ('zamir-borubaev', 3.5, 3.5),
    ('stanislav-shumilin', 3.5, 3.5),
    ('ilzat-husainov', 3.5, 3.5),
    ('azat-mukaev', 3.5, 3.5),
    ('bek-kydyrgychov', 3.5, 3.5),
    ('abdurahman-niyazov', 3.5, 3.0),
    ('azat-sakebaev', 3.5, 3.0),
    ('dzhantay-otorbaev', 3.5, 3.0),
    ('mark-garreta-navo', 3.5, 3.5),
    ('kamil-yakupov', 3.5, 3.5),
    ('alan-adzhibekov', 3.5, 3.5),
    ('aman-kanaev', 3.5, 3.0),
    ('argen-shakidiev', 3.5, 3.0),
    ('aleksandr-gabaguev', 3.5, 3.0),
    ('taalay-esenamanov', 3.5, 3.0),
    ('yakov-yudin', 3.5, 3.0),
    ('azat-kubanychbek-uulu', 3.5, 3.0),
    ('vitaliy-valyaev', 3.5, 3.5),
    ('askar-zhumagulov', 3.5, 3.5),
    ('tilegen-mamyrkaliev', 3.5, 3.5),
    ('ibragim-koshoybekov', 3.5, 3.0),
    ('azamat-nurdinov', 3.5, 3.0),
    ('evgeniy-osipov', 3.5, 3.0),
    ('altynbek-zhanybekov', 3.5, 3.5),
    ('ilyas-kydyraliev', 3.5, 3.5),
    ('murat-alaychyev', 3.5, 3.0),
    ('zhakshylyk-aytbaev', 3.5, 3.0),
    ('sergey-levin', 3.5, 3.5),
    ('elnur-omurzakov', 3.5, 3.0),
    ('nurbek-nurbekov', 3.5, 3.5),
    ('zhanat-kydraliev', 3.5, 3.0),
    ('faruh-suleymanov', 3.5, 3.0),
    ('bekzat-imenov', 3.5, 3.0),
    ('shavkat-mihmanov', 3.5, 3.0),
    ('stanislav-danilevich', 3.5, 3.5),
    ('dilshat-bazhanov', 3.5, 3.5),
    ('yaroslav-mironov', 3.5, 3.0),
    ('nurlan-azygaliev', 3.5, 3.5),
    ('ravil-sayfutdinov', 3.5, 3.0),
    ('ermek-abakirov', 3.5, 3.0),
    ('amir-kanaev', 3.0, 3.0),
    ('salih-ismailov', 3.0, 3.0),
    ('azat-bazarkulov', 3.0, 3.0),
    ('bahram-mambetov', 3.0, 3.0),
    ('dmitriy-dudrin', 3.0, 3.0),
    ('ahmedzhan-adzhuev', 3.0, 3.0),
    ('dmitriy-pak', 3.0, 3.0),
    ('salman-beyshenaliev', 3.0, 3.0),
    ('bakyt-kapakov', 3.0, 3.0),
    ('aydin-daniyarov', 3.0, 3.0),
    ('atay-begaliev', 3.0, 3.0),
    ('vladislav-abrosimov', 3.0, 3.0),
    ('bekzhan-kylychbekov', 3.0, 3.0),
    ('adil-valimamedov', 3.0, 3.0),
    ('alier-mahmuthodzhaev', 3.0, 3.0),
    ('dilshat-nurdinov', 3.0, 3.0),
    ('azatbek-musaev', 3.0, 3.0),
    ('timur-uzagaliev', 3.0, 3.0),
    ('musa-zhanybekov', 3.0, 3.0),
    ('iskender-kadyrov', 3.0, 3.0),
    ('askar-abaskanov', 3.0, 3.0),
    ('aleksey-pyankov', 3.0, 3.0),
    ('eren-kamchibekov', 3.0, 3.0),
    ('sultan-ibragimov', 3.0, 3.0),
    ('nur-tulebaev', 3.0, 3.0),
    ('ivan-shvyrov', 3.0, 3.0),
    ('adlet-mamyrov', 3.0, 3.0),
    ('rustam-ushur', 3.0, 3.0),
    ('sanzhar-ergeshaliev', 3.0, 3.0),
    ('allayar-nasyrov', 3.0, 3.0),
    ('suvar-ayylchiev', 3.0, 3.0),
    ('aleksandr-kim', 3.0, 3.0),
    ('akylbek-tentiev', 3.0, 3.0),
    ('omurbek-zholdoshev', 3.0, 3.0),
    ('sardar-artykbaev', 3.0, 3.0),
    ('nursultan-ulukbekov', 3.0, 3.0),
    ('faruh-suleymanov', 3.0, 3.0),
    ('imar-kamalov', 3.0, 3.0),
    ('vladimir-antonenko', 3.0, 3.0),
    ('roman-valyaev', 3.0, 3.0),
    ('beksultan-rustamov', 2.5, 2.5),
    ('bekmamat-nurmamat-uulu', 2.5, 2.5),
    ('erbol-abdyakimov', 2.5, 2.5),
    ('altynbek-zhoogachiev', 2.5, 2.5),
    ('atay-isaev', 2.5, 2.5),
    ('nursultan-zhunusov', 2.5, 2.5),
    ('nurmat-sakebaev', 2.5, 2.5),
    ('aydar-orozbaev', 2.5, 2.5),
    ('timofey-kim', 2.5, 2.5),
    ('sultan-ayylchiev', 2.5, 2.5),
    ('nikita-potrimaylo', 2.5, 2.5),
    ('nelli-buyuklyanova', 5.0, 5.25),
    ('arina-belyaeva', 5.0, 5.0),
    ('albina-sulaymanova', 5.0, 5.0),
    ('sofya-blagovisnaya', 4.5, 4.5),
    ('anastasiya-trofimushkina', 4.25, 4.25),
    ('roza-isabekova', 4.25, 4.25),
    ('asel-makaeva', 4.25, 4.25),
    ('aysuluu-chokoeva', 4.0, 4.25),
    ('leyli-blagovisnaya', 4.0, 4.25),
    ('natalya-klimenko', 4.0, 4.25),
    ('tat-yana-nechaeva', 4.0, 4.0),
    ('gulmira-orozalieva', 4.0, 4.0),
    ('shirin-karimova', 4.0, 4.25),
    ('marianna-proskurina', 4.0, 4.0),
    ('ayday-orozbaeva', 4.0, 4.0),
    ('yana-belekova', 4.0, 4.0),
    ('anastasiya-adzhibekova', 4.0, 4.0),
    ('adel-dzhayloeva', 4.0, 4.0),
    ('larisa-yancharuk', 4.0, 4.0),
    ('kalima-askarova', 4.0, 3.7),
    ('barno-tursunova', 3.7, 4.0),
    ('elizaveta-aleksandra-ponomareva', 3.7, 3.5),
    ('ekateria-titova', 3.7, 3.7),
    ('natalya-temirbaeva', 3.7, 3.7),
    ('tatyana-andreevskaya', 3.7, 3.7),
    ('nataliya-tsurban', 3.7, 3.5),
    ('zarima-baygubatova', 3.7, 3.5),
    ('ayzhan-temiralieva', 3.7, 3.0),
    ('keremet-begmatova', 3.7, 3.5),
    ('asel-isabekova', 3.7, 3.5),
    ('nazgul-kerimalieva', 3.7, 3.5),
    ('valeriya-hegay', 3.7, 3.5),
    ('elena-kan', 3.7, 3.5),
    ('amina-kurbanova', 3.7, 3.5),
    ('valeriya-pak', 3.7, 3.5),
    ('sveta-poharel', 3.7, 3.5),
    ('aleksandra-muchkina', 3.7, 3.5),
    ('narmina-ahmatova', 3.7, 3.5),
    ('akzholtoy-isabekova', 3.5, 3.5),
    ('natalya-seytmuratova', 3.5, 3.5),
    ('svetlana-hanazhenko', 3.5, 3.5),
    ('adelya-kamchybekova', 3.5, 3.5),
    ('nella-kotelnikova', 3.5, 3.5),
    ('aysuluu-orokova', 3.5, 3.5),
    ('zulayka-talasbek-kyzy', 3.5, 3.5),
    ('shoola-baysaeva', 3.5, 3.5),
    ('aziza-musaeva', 3.5, 3.0),
    ('asel-ashimova', 3.5, 3.0),
    ('aydana-aktanova', 3.5, 3.0),
    ('malika-shamil', 3.5, 3.0),
    ('altynay-omuralieva', 3.5, 3.0),
    ('akzholtoy-bolotbekova', 3.5, 3.0),
    ('bermet-samsalieva', 3.5, 3.0),
    ('mariya-gurina', 3.5, 3.0),
    ('kalicha-taygurova', 3.5, 3.0),
    ('elizaveta-pilipenko', 3.5, 3.0),
    ('darya-zinina', 3.5, 3.0),
    ('nurzhamal-dzhanibekova', 3.5, 3.0),
    ('olga-petrovskaya', 3.5, 3.0),
    ('meerim-zhumabekova', 3.5, 3.0),
    ('kanykey-tursunbaeva', 3.5, 3.0),
    ('aydina-aytmatova', 3.5, 3.0),
    ('kanyshay-badretdinova', 3.5, 3.0),
    ('ayday-akmatalieva', 3.5, 3.0),
    ('zuhra-muralieva', 3.5, 3.0),
    ('burul-rakisheva', 3.5, 3.0),
    ('aygerim-sarieva', 3.0, 3.0),
    ('yana-eresko', 3.0, 3.0),
    ('diana-imanahunova', 3.0, 3.0),
    ('aygerim-alizhanova', 3.0, 3.0),
    ('asel-orokova', 3.0, 3.0),
    ('aliya-abaskanova', 3.0, 3.0),
    ('nailya-osmonova', 3.0, 3.0),
    ('saliya-ustemirova', 3.0, 3.0),
    ('kasiet-samsalieva', 3.0, 3.0),
    ('ayzat-torobekova', 3.0, 3.0),
    ('aida-nogoybaeva', 3.0, 3.0),
    ('aleksandra-panfilova', 3.0, 3.0),
    ('tahmina-gaparova', 3.0, 3.0),
    ('aysha-turdumambetova', 3.0, 3.0),
    ('sonya-orokova', 3.0, 3.0),
    ('asel-abdygulova', 3.0, 3.0),
    ('tolgonay-aytkulova', 3.0, 3.0),
    ('madina-kadyrova', 3.0, 3.0),
    ('dana-kurmanalieva', 3.0, 3.0),
    ('saykal-niyazova', 3.0, 3.0),
    ('erkaim-shambetova', 3.0, 3.0),
    ('diana-imanahunova', 3.0, 3.0),
    ('nargiza-sakebaeva', 3.0, 3.0),
    ('ayzana-toguzbaeva', 3.0, 3.0),
    ('ramina-ushur', 3.0, 3.0),
    ('aysuluu-erkulova', 3.0, 3.0),
    ('tatyana-mashenskaya', 3.0, 3.0),
    ('gulsan-galieva', 3.0, 3.0),
    ('feyruza-ikram', 2.5, 3.0),
    ('ekaterina-saveleva', 2.5, 3.0),
    ('altynay-dzhamanbaeva', 2.5, 3.0),
    ('yrysgul-sakebaeva', 2.5, 3.0),
    ('viktoriya-han', 2.5, 3.0),
    ('aisha-nurbekova', 2.5, 3.0),
    ('elina-samanova', 2.5, 3.0),
    ('dana-kurmanalieva', 2.5, 3.0)
       ) AS н(id, од, пар)
WHERE p.id = н.id;

-- ---- 3. Новые карточки из списка ----

INSERT INTO players (id, name, gender, ntrp_singles, ntrp_doubles)
VALUES ('mirsaid-mirdzhaliev', 'Мирсаид Мирджалиев', 'men', 4.0, 4.25),
       ('bulat-tsoy', 'Булат Цой', 'men', 3.7, 3.7),
       ('ravil-galinurov', 'Равиль Галинуров', 'men', 3.5, 3.5),
       ('sultan-sanzharov', 'Султан Санжаров', 'men', 3.5, 3.5),
       ('evgeniy-gorskih', 'Евгений Горских', 'men', 3.5, 3.5),
       ('daniyar-lyamin', 'Данияр Лямин', 'men', 3.5, 3.5),
       ('esendiyar-adylov', 'Эсендияр Адылов', 'men', 3.5, 3.5),
       ('adham-ubaydullaev', 'Адхам Убайдуллаев', 'men', 3.5, 3.0),
       ('anvar-nasyrov', 'Анвар Насыров', 'men', 3.5, 3.5),
       ('rustam-nasyrov', 'Рустам Насыров', 'men', 3.5, 3.5),
       ('elzar-azhibaev', 'Элзар Ажибаев', 'men', 3.5, 3.0),
       ('astar-bekturov', 'Астар Бектуров', 'men', 3.0, 3.0),
       ('tagaybek-uulu-ulan', 'Тагайбек уулу Улан', 'men', 3.0, 3.0),
       ('kudaybergenov-askar', 'Кудайбергенов Аскар', 'men', 3.0, 3.0),
       ('daniyar-bekboev', 'Данияр Бекбоев', 'men', 3.0, 3.0),
       ('sadyrbek-tovkeev', 'Садырбек Товкеев', 'men', 3.0, 3.0),
       ('andrey-mokeev', 'Андрей Мокеев', 'men', 3.0, 3.0),
       ('ashat-kerimbekov', 'Асхат Керимбеков', 'men', 3.0, 3.0),
       ('timur-baygubatov', 'Тимур Байгубатов', 'men', 2.5, 2.5),
       ('artur-amanbekov', 'Артур Аманбеков', 'men', 2.5, 2.5),
       ('omuradil-sydykov', 'Омурадил Сыдыков', 'men', 2.5, 2.5),
       ('sultan-matiev', 'Султан Матиев', 'men', 2.5, 2.5),
       ('eynar-moydunov', 'Эйнар Мойдунов', 'men', 2.5, 2.5),
       ('damirbek-kydykov', 'Дамирбек Кыдыков', 'men', 2.5, 2.5),
       ('tilektesh-zhetigenov', 'Тилектеш Жетигенов', 'men', 2.5, 2.5),
       ('rustam-shaygardanov', 'Рустам Шайгарданов', 'men', 2.5, 2.5),
       ('malik-mansurov', 'Малик Мансуров', 'men', 2.5, 2.5),
       ('denis-vorontsov', 'Денис Воронцов', 'men', 2.5, 2.5),
       ('ivan-troshin', 'Иван Трошин', 'men', 2.5, 2.5),
       ('chingis-sadybaev', 'Чингис Садыбаев', 'men', 2.5, 2.5),
       ('azamat-omuraliev', 'Азамат Омуралиев', 'men', 2.5, 2.5),
       ('ermek-attakurov', 'Эрмек Аттакуров', 'men', 2.5, 2.5),
       ('anvar-ahmedbaev', 'Анвар Ахмедбаев', 'men', 2.5, 2.5),
       ('zhanybek-kaparov', 'Жаныбек Капаров', 'men', 2.5, 2.5),
       ('ulan-kasenov', 'Улан Касенов', 'men', 2.5, 2.5),
       ('nikita-nischuk', 'Никита Нищук', 'men', 2.5, 2.5),
       ('aleksey-li', 'Алексей Ли', 'men', 2.5, 2.5),
       ('vladimir-kim', 'Владимир Ким', 'men', 2.5, 2.5),
       ('nurshat-iminov', 'Нуршат Иминов', 'men', 2.5, 2.5),
       ('derbishaliev-arzymat', 'Дербишалиев Арзымат', 'men', 2.5, 2.5),
       ('bobirzhon-madalinov', 'Бобиржон Мадалинов', 'men', 2.5, 2.5),
       ('adilet-asanov', 'Адилет Асанов', 'men', 2.5, 2.5),
       ('saliev-aziz', 'Салиев Азиз', 'men', 2.5, 2.5),
       ('temirlan-tulegenov', 'Темирлан Тулегенов', 'men', 2.5, 2.5),
       ('bolot-duyshenbekov', 'Болот Дуйшенбеков', 'men', 2.5, 2.5),
       ('ulan-nurbekov', 'Улан Нурбеков', 'men', 2.5, 2.5),
       ('larisa-safronova', 'Лариса Сафронова', 'women', 4.0, 4.0),
       ('karakoz-bolotbekova', 'Каракоз Болотбекова', 'women', 4.0, 4.0),
       ('rahmatulina-liliya', 'Рахматулина Лилия', 'women', 3.7, 3.5),
       ('tabaldieva-aykanysh', 'Табалдиева Айканыш', 'women', 3.0, 3.0),
       ('nuriza-momunova', 'Нуриза Момунова', 'women', 2.5, 3.0),
       ('aliya-orokova', 'Алия Орокова', 'women', 2.5, 3.0),
       ('alina-zhakypova', 'Алина Жакыпова', 'women', 2.5, 3.0),
       ('alina-fasahutdinova', 'Алина Фасахутдинова', 'women', 2.5, 3.0),
       ('aleksandra-samaganova', 'Александра Самаганова', 'women', 2.5, 3.0),
       ('alina-osmonova', 'Алина Осмонова', 'women', 2.5, 3.0),
       ('diana-aytova', 'Диана Айтова', 'women', 2.5, 3.0),
       ('aydana-abishova', 'Айдана Абишова', 'women', 2.5, 3.0),
       ('adilya-mammadova', 'Адиля Маммадова', 'women', 2.5, 3.0),
       ('firuza-chinshaylo', 'Фируза Чиншайло', 'women', 2.5, 3.0),
       ('diana-dzhanusakova', 'Диана Джанусакова', 'women', 2.5, 3.0) ON CONFLICT (id) DO
UPDATE
    SET ntrp_singles = excluded.ntrp_singles,
    ntrp_doubles = excluded.ntrp_doubles,
    is_guest = false;

-- ---- 4. Кого нет в списке — тот гость ----
--
-- Список NTRP и есть список игроков клуба. Остальные — гости: рейтинга у них
-- нет, страницы тоже, в сетке имя показывается без ссылки.

UPDATE players
   SET is_guest = true, ntrp_singles = NULL, ntrp_doubles = NULL
 WHERE id NOT IN (
        'atham-israilov',
        'anton-sevalnev',
        'aleksandr-logvinenko',
        'erlan-shekerbekov',
        'aziz-bazakov',
        'rufat-mirdzhaliev',
        'eldar-safiullin',
        'roman-dolgushin',
        'ruslan-kuldzhaev',
        'ermek-aratov',
        'karim-imanhodzhaev',
        'aymen-azygaliev',
        'tengiz-atahanov',
        'arsen-umurzakov',
        'nikita-boykov',
        'baturhan-usenov',
        'kirill-leontev',
        'ruslan-andreev',
        'mirdias-tumenbaev',
        'kamil-murakov',
        'ildiyar-murataliev',
        'ilan-aatabaev',
        'mihail-chertkov',
        'azim-isakov',
        'furkat-sadykov',
        'rashid-seyitov',
        'ramil-miftahutdinov',
        'igor-muratov',
        'konstantin-lazarev',
        'avtandil-ernest',
        'roman-gudi',
        'rustam-faizov',
        'ulugbek-salymbekov',
        'daniyar-atahanov',
        'azis-myrzaev',
        'ilya-velikorodnyy',
        'anvar-askarov',
        'sergey-sokolov',
        'bakyt-kayypov',
        'azamat-dzhumabaev',
        'almazbek-emilkanov',
        'evgeniy-tsoy',
        'ravil-miftahutdinov',
        'daniel-gubler',
        'erbol-kylychev',
        'dmitriy-bondarev',
        'yura-yun',
        'zakir-nazarov',
        'hamit-karaketov',
        'dastan-omuraliev',
        'ravil-rahmatulin',
        'rustam-suleymanov',
        'aleksandr-fomin',
        'vladislav-kim',
        'erlan-sydykov',
        'ernest-takirov',
        'aydar-usmanov',
        'alymbek-orokov',
        'esen-azimov',
        'iskender-kurmanov',
        'kadyrbek-adiev',
        'zakir-gudadzhanov',
        'amir-bazhanov',
        'eldiyar-boruev',
        'kanat-abdrahmanov',
        'kayrat-karakeev',
        'arslan-dzhoroev',
        'sabyrbek-esenbekov',
        'seytek-chalbaev',
        'igor-hanganu',
        'ulukbek-bekbosunov',
        'abdikiim-mahmutov',
        'farruh-mavlitov',
        'avanes-balyan',
        'erkin-isakov',
        'vitaliy-kachala',
        'andrey-lebedev',
        'ivan-korabelnikov',
        'syngyz-ismatov',
        'aybek-zholdoshbekov',
        'edil-dzhanybekov',
        'temirbek-musaev',
        'kamil-atykanov',
        'danil-bondar',
        'yan-skazka',
        'etan-patek',
        'denis-ens',
        'denis-li',
        'sardar-umarov',
        'ermamat-matosmonov',
        'iskender-seydimatov',
        'murat-noruzbaev',
        'kerimbaev-erkin',
        'zamir-borubaev',
        'stanislav-shumilin',
        'ilzat-husainov',
        'azat-mukaev',
        'bek-kydyrgychov',
        'abdurahman-niyazov',
        'azat-sakebaev',
        'dzhantay-otorbaev',
        'mark-garreta-navo',
        'kamil-yakupov',
        'alan-adzhibekov',
        'aman-kanaev',
        'argen-shakidiev',
        'aleksandr-gabaguev',
        'taalay-esenamanov',
        'yakov-yudin',
        'azat-kubanychbek-uulu',
        'vitaliy-valyaev',
        'askar-zhumagulov',
        'tilegen-mamyrkaliev',
        'ibragim-koshoybekov',
        'azamat-nurdinov',
        'evgeniy-osipov',
        'altynbek-zhanybekov',
        'ilyas-kydyraliev',
        'murat-alaychyev',
        'zhakshylyk-aytbaev',
        'sergey-levin',
        'elnur-omurzakov',
        'nurbek-nurbekov',
        'zhanat-kydraliev',
        'faruh-suleymanov',
        'bekzat-imenov',
        'shavkat-mihmanov',
        'stanislav-danilevich',
        'dilshat-bazhanov',
        'yaroslav-mironov',
        'nurlan-azygaliev',
        'ravil-sayfutdinov',
        'ermek-abakirov',
        'amir-kanaev',
        'salih-ismailov',
        'azat-bazarkulov',
        'bahram-mambetov',
        'dmitriy-dudrin',
        'ahmedzhan-adzhuev',
        'dmitriy-pak',
        'salman-beyshenaliev',
        'bakyt-kapakov',
        'aydin-daniyarov',
        'atay-begaliev',
        'vladislav-abrosimov',
        'bekzhan-kylychbekov',
        'adil-valimamedov',
        'alier-mahmuthodzhaev',
        'dilshat-nurdinov',
        'azatbek-musaev',
        'timur-uzagaliev',
        'musa-zhanybekov',
        'iskender-kadyrov',
        'askar-abaskanov',
        'aleksey-pyankov',
        'eren-kamchibekov',
        'sultan-ibragimov',
        'nur-tulebaev',
        'ivan-shvyrov',
        'adlet-mamyrov',
        'rustam-ushur',
        'sanzhar-ergeshaliev',
        'allayar-nasyrov',
        'suvar-ayylchiev',
        'aleksandr-kim',
        'akylbek-tentiev',
        'omurbek-zholdoshev',
        'sardar-artykbaev',
        'nursultan-ulukbekov',
        'faruh-suleymanov',
        'imar-kamalov',
        'vladimir-antonenko',
        'roman-valyaev',
        'beksultan-rustamov',
        'bekmamat-nurmamat-uulu',
        'erbol-abdyakimov',
        'altynbek-zhoogachiev',
        'atay-isaev',
        'nursultan-zhunusov',
        'nurmat-sakebaev',
        'aydar-orozbaev',
        'timofey-kim',
        'sultan-ayylchiev',
        'nikita-potrimaylo',
        'nelli-buyuklyanova',
        'arina-belyaeva',
        'albina-sulaymanova',
        'sofya-blagovisnaya',
        'anastasiya-trofimushkina',
        'roza-isabekova',
        'asel-makaeva',
        'aysuluu-chokoeva',
        'leyli-blagovisnaya',
        'natalya-klimenko',
        'tat-yana-nechaeva',
        'gulmira-orozalieva',
        'shirin-karimova',
        'marianna-proskurina',
        'ayday-orozbaeva',
        'yana-belekova',
        'anastasiya-adzhibekova',
        'adel-dzhayloeva',
        'larisa-yancharuk',
        'kalima-askarova',
        'barno-tursunova',
        'elizaveta-aleksandra-ponomareva',
        'ekateria-titova',
        'natalya-temirbaeva',
        'tatyana-andreevskaya',
        'nataliya-tsurban',
        'zarima-baygubatova',
        'ayzhan-temiralieva',
        'keremet-begmatova',
        'asel-isabekova',
        'nazgul-kerimalieva',
        'valeriya-hegay',
        'elena-kan',
        'amina-kurbanova',
        'valeriya-pak',
        'sveta-poharel',
        'aleksandra-muchkina',
        'narmina-ahmatova',
        'akzholtoy-isabekova',
        'natalya-seytmuratova',
        'svetlana-hanazhenko',
        'adelya-kamchybekova',
        'nella-kotelnikova',
        'aysuluu-orokova',
        'zulayka-talasbek-kyzy',
        'shoola-baysaeva',
        'aziza-musaeva',
        'asel-ashimova',
        'aydana-aktanova',
        'malika-shamil',
        'altynay-omuralieva',
        'akzholtoy-bolotbekova',
        'bermet-samsalieva',
        'mariya-gurina',
        'kalicha-taygurova',
        'elizaveta-pilipenko',
        'darya-zinina',
        'nurzhamal-dzhanibekova',
        'olga-petrovskaya',
        'meerim-zhumabekova',
        'kanykey-tursunbaeva',
        'aydina-aytmatova',
        'kanyshay-badretdinova',
        'ayday-akmatalieva',
        'zuhra-muralieva',
        'burul-rakisheva',
        'aygerim-sarieva',
        'yana-eresko',
        'diana-imanahunova',
        'aygerim-alizhanova',
        'asel-orokova',
        'aliya-abaskanova',
        'nailya-osmonova',
        'saliya-ustemirova',
        'kasiet-samsalieva',
        'ayzat-torobekova',
        'aida-nogoybaeva',
        'aleksandra-panfilova',
        'tahmina-gaparova',
        'aysha-turdumambetova',
        'sonya-orokova',
        'asel-abdygulova',
        'tolgonay-aytkulova',
        'madina-kadyrova',
        'dana-kurmanalieva',
        'saykal-niyazova',
        'erkaim-shambetova',
        'diana-imanahunova',
        'nargiza-sakebaeva',
        'ayzana-toguzbaeva',
        'ramina-ushur',
        'aysuluu-erkulova',
        'tatyana-mashenskaya',
        'gulsan-galieva',
        'feyruza-ikram',
        'ekaterina-saveleva',
        'altynay-dzhamanbaeva',
        'yrysgul-sakebaeva',
        'viktoriya-han',
        'aisha-nurbekova',
        'elina-samanova',
        'dana-kurmanalieva',
        'mirsaid-mirdzhaliev',
        'bulat-tsoy',
        'ravil-galinurov',
        'sultan-sanzharov',
        'evgeniy-gorskih',
        'daniyar-lyamin',
        'esendiyar-adylov',
        'adham-ubaydullaev',
        'anvar-nasyrov',
        'rustam-nasyrov',
        'elzar-azhibaev',
        'astar-bekturov',
        'tagaybek-uulu-ulan',
        'kudaybergenov-askar',
        'daniyar-bekboev',
        'sadyrbek-tovkeev',
        'andrey-mokeev',
        'ashat-kerimbekov',
        'timur-baygubatov',
        'artur-amanbekov',
        'omuradil-sydykov',
        'sultan-matiev',
        'eynar-moydunov',
        'damirbek-kydykov',
        'tilektesh-zhetigenov',
        'rustam-shaygardanov',
        'malik-mansurov',
        'denis-vorontsov',
        'ivan-troshin',
        'chingis-sadybaev',
        'azamat-omuraliev',
        'ermek-attakurov',
        'anvar-ahmedbaev',
        'zhanybek-kaparov',
        'ulan-kasenov',
        'nikita-nischuk',
        'aleksey-li',
        'vladimir-kim',
        'nurshat-iminov',
        'derbishaliev-arzymat',
        'bobirzhon-madalinov',
        'adilet-asanov',
        'saliev-aziz',
        'temirlan-tulegenov',
        'bolot-duyshenbekov',
        'ulan-nurbekov',
        'larisa-safronova',
        'karakoz-bolotbekova',
        'rahmatulina-liliya',
        'tabaldieva-aykanysh',
        'nuriza-momunova',
        'aliya-orokova',
        'alina-zhakypova',
        'alina-fasahutdinova',
        'aleksandra-samaganova',
        'alina-osmonova',
        'diana-aytova',
        'aydana-abishova',
        'adilya-mammadova',
        'firuza-chinshaylo',
        'diana-dzhanusakova'
 );

-- ---- 5. Гости, за которыми ничего не тянется, — удаляем ----
--
-- Проверяем по самим записям, а не по счётчикам побед в карточке: счётчики
-- обновляются не всегда, и по ним карточка выглядела пустой, хотя матчи есть.

DELETE FROM players p
 WHERE p.is_guest
   AND NOT EXISTS (SELECT 1 FROM matches m
                    WHERE m.player1_id = p.id OR m.player2_id = p.id OR m.winner_id = p.id)
   AND NOT EXISTS (SELECT 1 FROM tournament_registrations r
                    WHERE r.player_id = p.id OR r.partner_id = p.id)
   AND NOT EXISTS (SELECT 1 FROM tournament_results tr
                    WHERE tr.player_id = p.id OR tr.partner_id = p.id)
   AND NOT EXISTS (SELECT 1 FROM challenges c
                    WHERE c.challenger_player_id = p.id OR c.opponent_player_id = p.id)
   AND NOT EXISTS (SELECT 1 FROM live_matches l
                    WHERE l.player1_id = p.id OR l.player2_id = p.id)
   AND NOT EXISTS (SELECT 1 FROM rating_history rh WHERE rh.player_id = p.id)
   AND NOT EXISTS (SELECT 1 FROM profiles pr WHERE pr.player_id = p.id);

COMMIT;

-- Что получилось
SELECT count(*) FILTER (WHERE NOT is_guest) AS игроков_клуба, count(*) FILTER (WHERE is_guest)     AS гостей, count(*) FILTER (WHERE ntrp_singles IS NOT NULL) AS с_рейтингом, count(*) AS всего
FROM players;
