-- ============================================================
-- ТБШ Futures 2026 — сетка целиком, как на бумаге
-- ============================================================
--
-- Здесь записано готовое состояние всех 192 клеток: кто в клетке стоит, кто
-- победил и с каким счётом. Считалось это не в базе, а отдельно — по листу
-- Excel и по PDF «ТБШ FUTURES_турнирная сетка», который новее таблицы.
--
-- Почему так, а не счетами по одному. Сетка «все места» пересчитывается сама
-- при каждой записи результата, и в нижней половине бумажная сетка
-- расходится с нашим правилом: там одна лишняя пустая линия, и пары ниже
-- съехали на строку. Пока я вписывал результаты по очереди, пересчёт каждый
-- раз тянул людей по своему правилу, и сетка разъезжалась. Поэтому итог
-- посчитан целиком и записывается как есть, а пересчёт на это время выключен.
--
-- Из 98 матчей бумаги легло 96. Два вписать руками через админку:
--   Салих Исмаилов — Ахмеджан Аджуев 4/6 6/3 10/4 (за 9 место)
--   Атай Бегалиев — Бексултан Рустамов 6/2 4/6 10/4 (за 25 место)
--
-- Запускать можно повторно.
--
-- Файл меняет базу. Читающие запросы — в tbsh-2026-check.sql.

ALTER TABLE public.matches DISABLE TRIGGER trg_advance_bracket;

UPDATE matches m
   SET player1_id = s.p1, player2_id = s.p2,
       seed1 = s.s1, seed2 = s.s2,
       winner_id = s.winner,
       score = s.score,
       status = CASE WHEN s.winner IS NOT NULL THEN 'completed' ELSE 'upcoming' END,
       played_at = CASE WHEN s.winner IS NOT NULL THEN now() ELSE NULL END
  FROM (VALUES
    (1::integer,1::integer,'sergey-levin'::text,NULL::text,1::integer,NULL::integer,'sergey-levin'::text,'BYE'::text),
    (1,2,'sultan-ibragimov','bekzhan-kylychbekov',33,32,'bekzhan-kylychbekov','6/1 6/2'),
    (1,3,'timofey-kim','dmitriy-pak',17,48,'dmitriy-pak','6/2 6/2'),
    (1,4,'altynbek-zhoogachiev','alier-mahmuthodzhaev',49,16,'alier-mahmuthodzhaev','6/2 6/1'),
    (1,5,'imar-kamalov',NULL,9,NULL,'imar-kamalov','BYE'),
    (1,6,'ravil-sayfutdinov','aleksandr-kim',41,24,'ravil-sayfutdinov','6/3 6/3'),
    (1,7,'nursultan-zhunusov','rustam-ushur',25,40,'nursultan-zhunusov','6/3 6/3'),
    (1,8,'ahmedzhan-adzhuev',NULL,8,NULL,'ahmedzhan-adzhuev','BYE'),
    (1,9,'nurbek-nurbekov',NULL,5,NULL,'nurbek-nurbekov','BYE'),
    (1,10,'timur-uzagaliev','allayar-nasyrov',37,28,'timur-uzagaliev','6/2 6/4'),
    (1,11,'sanzhar-ergeshaliev','bakyt-kapakov',21,44,'bakyt-kapakov','6/3 6/4'),
    (1,12,'eren-kamchibekov','sultan-ayylchiev',53,12,'eren-kamchibekov','6/1 6/3'),
    (1,13,'askar-abaskanov','iskender-kadyrov',13,52,'iskender-kadyrov','6/4 6/2'),
    (1,14,'atay-begaliev','vladimir-antonenko',45,20,'atay-begaliev','6/2 6/4'),
    (1,15,'zhakshylyk-aytbaev','omurbek-zholdoshev',29,36,'zhakshylyk-aytbaev','2/6 6/3 7/3'),
    (1,16,'shavkat-mihmanov',NULL,4,NULL,'shavkat-mihmanov','BYE'),
    (1,17,'amir-kanaev',NULL,3,NULL,'amir-kanaev','BYE'),
    (1,18,'beksultan-rustamov',NULL,35,NULL,'beksultan-rustamov','BYE'),
    (1,19,'suvar-ayylchiev','azatbek-musaev',19,46,'azatbek-musaev','6/3 6/3'),
    (1,20,'bekmamat-nurmamat-uulu','nur-tulebaev',51,14,'nur-tulebaev','6/0 6/0'),
    (1,21,'aydin-daniyarov','erbol-abdyakimov',11,54,'erbol-abdyakimov','2/6 7/5 10/3'),
    (1,22,'altynbek-zhanybekov','roman-valyaev',43,22,'altynbek-zhanybekov','6/2 7/6 7/5'),
    (1,23,'musa-zhanybekov','salih-ismailov',27,38,'salih-ismailov','6/1 7/6'),
    (1,24,'murat-alaychyev',NULL,6,NULL,'murat-alaychyev','BYE'),
    (1,25,'bahram-mambetov',NULL,7,NULL,'bahram-mambetov','BYE'),
    (1,26,'nursultan-ulukbekov','atay-isaev',39,26,'nursultan-ulukbekov','6/1 6/3'),
    (1,27,'salman-beyshenaliev','aydar-orozbaev',23,42,'salman-beyshenaliev','6/3 6/4'),
    (1,28,'elnur-omurzakov','adil-valimamedov',55,10,'elnur-omurzakov','7/5 6/3'),
    (1,29,NULL,'azat-kubanychbek-uulu',NULL,50,'azat-kubanychbek-uulu','BYE'),
    (1,30,'adlet-mamyrov','nurmat-sakebaev',47,18,'nurmat-sakebaev','6/0 6/3'),
    (1,31,NULL,'ulan-tagaybek-uulu',NULL,34,'ulan-tagaybek-uulu','BYE'),
    (1,32,'azat-bazarkulov',NULL,2,NULL,'azat-bazarkulov','BYE'),
    (2,1,'sergey-levin','bekzhan-kylychbekov',1,32,'sergey-levin','6/0 6/0'),
    (2,2,'dmitriy-pak','alier-mahmuthodzhaev',48,16,'dmitriy-pak','6/0 6/1'),
    (2,3,'imar-kamalov','ravil-sayfutdinov',9,41,'ravil-sayfutdinov','6/3 6/0'),
    (2,4,'nursultan-zhunusov','ahmedzhan-adzhuev',25,8,'ahmedzhan-adzhuev','6/2 6/1'),
    (2,5,'nurbek-nurbekov','timur-uzagaliev',5,37,'nurbek-nurbekov','6/3 6/0'),
    (2,6,'bakyt-kapakov','eren-kamchibekov',44,53,'bakyt-kapakov','6/0 3/6 10/4'),
    (2,7,'iskender-kadyrov','atay-begaliev',52,45,'iskender-kadyrov','6/3 6/1'),
    (2,8,'zhakshylyk-aytbaev','shavkat-mihmanov',29,4,'shavkat-mihmanov','7/5 4/6 7/5'),
    (2,9,'amir-kanaev','beksultan-rustamov',3,35,'amir-kanaev','6/4 6/3'),
    (2,10,'azatbek-musaev','nur-tulebaev',46,14,'azatbek-musaev','7/6(7-5) 6/2'),
    (2,11,'erbol-abdyakimov','altynbek-zhanybekov',54,43,'altynbek-zhanybekov','6/1 6/0'),
    (2,12,'salih-ismailov','murat-alaychyev',38,6,'salih-ismailov','1/6 6/4 10/5'),
    (2,13,'bahram-mambetov','nursultan-ulukbekov',7,39,'bahram-mambetov','6/3 6/1'),
    (2,14,'salman-beyshenaliev','elnur-omurzakov',23,55,'elnur-omurzakov','6/1 6/3'),
    (2,15,'azat-kubanychbek-uulu','nurmat-sakebaev',50,18,'azat-kubanychbek-uulu','6/4 6/0'),
    (2,16,'ulan-tagaybek-uulu','azat-bazarkulov',34,2,'azat-bazarkulov','6/0 6/2'),
    (2,17,NULL,'sultan-ibragimov',NULL,33,'sultan-ibragimov','BYE'),
    (2,18,'timofey-kim','altynbek-zhoogachiev',17,49,'altynbek-zhoogachiev','6/1 4/6 7/5'),
    (2,19,NULL,'aleksandr-kim',NULL,24,'aleksandr-kim','BYE'),
    (2,20,'rustam-ushur',NULL,40,NULL,'rustam-ushur','BYE'),
    (2,21,NULL,'allayar-nasyrov',NULL,28,'allayar-nasyrov','BYE'),
    (2,22,'sanzhar-ergeshaliev','sultan-ayylchiev',21,12,'sanzhar-ergeshaliev','W/O'),
    (2,23,'askar-abaskanov','vladimir-antonenko',13,20,'vladimir-antonenko','6/1 6/0'),
    (2,24,'omurbek-zholdoshev',NULL,36,NULL,'omurbek-zholdoshev','BYE'),
    (2,25,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,26,'suvar-ayylchiev',NULL,19,NULL,'suvar-ayylchiev','BYE'),
    (2,27,'bekmamat-nurmamat-uulu','aydin-daniyarov',51,11,'aydin-daniyarov','6/3 6/3'),
    (2,28,'roman-valyaev','musa-zhanybekov',22,27,'musa-zhanybekov','W/O'),
    (2,29,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,30,'atay-isaev','aydar-orozbaev',26,42,'aydar-orozbaev','6/2 DEF'),
    (2,31,'adil-valimamedov',NULL,10,NULL,'adil-valimamedov','BYE'),
    (2,32,'adlet-mamyrov',NULL,47,NULL,'adlet-mamyrov','BYE'),
    (3,1,'sergey-levin','dmitriy-pak',1,48,'sergey-levin','6/1 6/1'),
    (3,2,'ravil-sayfutdinov','ahmedzhan-adzhuev',41,8,'ravil-sayfutdinov','7/6(7-3) 6/3'),
    (3,3,'nurbek-nurbekov','bakyt-kapakov',5,44,'nurbek-nurbekov','6/2 6/0'),
    (3,4,'iskender-kadyrov','shavkat-mihmanov',52,4,'shavkat-mihmanov','6/0 6/2'),
    (3,5,'amir-kanaev','azatbek-musaev',3,46,'amir-kanaev','6/4 6/3'),
    (3,6,'altynbek-zhanybekov','salih-ismailov',43,38,'altynbek-zhanybekov','W/O'),
    (3,7,'bahram-mambetov','elnur-omurzakov',7,55,'elnur-omurzakov','6/1 6/1'),
    (3,8,'azat-kubanychbek-uulu','azat-bazarkulov',50,2,'azat-kubanychbek-uulu','W/O'),
    (3,9,'bekzhan-kylychbekov','alier-mahmuthodzhaev',32,16,'bekzhan-kylychbekov','W/O'),
    (3,10,'imar-kamalov','nursultan-zhunusov',9,25,'imar-kamalov','6/2 6/2'),
    (3,11,'timur-uzagaliev','eren-kamchibekov',37,53,'eren-kamchibekov','6/4 6/4'),
    (3,12,'atay-begaliev','zhakshylyk-aytbaev',45,29,'zhakshylyk-aytbaev','2/6 6/3 6/2'),
    (3,13,'beksultan-rustamov','nur-tulebaev',35,14,'nur-tulebaev','6/1 6/4'),
    (3,14,'erbol-abdyakimov','murat-alaychyev',54,6,'murat-alaychyev','W/O'),
    (3,15,'nursultan-ulukbekov','salman-beyshenaliev',39,23,'salman-beyshenaliev','6/3 6/3'),
    (3,16,'nurmat-sakebaev','ulan-tagaybek-uulu',18,34,'ulan-tagaybek-uulu','W/O'),
    (3,17,'sultan-ibragimov','altynbek-zhoogachiev',33,49,'sultan-ibragimov','W/O'),
    (3,18,'aleksandr-kim','rustam-ushur',24,40,'aleksandr-kim','6/4 6/1'),
    (3,19,'allayar-nasyrov','sanzhar-ergeshaliev',28,21,'allayar-nasyrov','W/O'),
    (3,20,'vladimir-antonenko','omurbek-zholdoshev',20,36,'omurbek-zholdoshev','W/O'),
    (3,21,NULL,'suvar-ayylchiev',NULL,19,'suvar-ayylchiev','BYE'),
    (3,22,'aydin-daniyarov','musa-zhanybekov',11,27,'musa-zhanybekov','6/3 6/3'),
    (3,23,NULL,'aydar-orozbaev',NULL,42,'aydar-orozbaev','BYE'),
    (3,24,'adil-valimamedov','adlet-mamyrov',10,47,'adlet-mamyrov','4/6 6/3 6/4'),
    (3,25,NULL,'timofey-kim',NULL,17,'timofey-kim','BYE'),
    (3,26,NULL,NULL,NULL,NULL,NULL,NULL),
    (3,27,NULL,'sultan-ayylchiev',NULL,12,'sultan-ayylchiev','BYE'),
    (3,28,'askar-abaskanov',NULL,13,NULL,'askar-abaskanov','BYE'),
    (3,29,NULL,NULL,NULL,NULL,NULL,NULL),
    (3,30,'bekmamat-nurmamat-uulu','roman-valyaev',51,22,NULL,NULL),
    (3,31,NULL,'atay-isaev',NULL,26,'atay-isaev','BYE'),
    (3,32,NULL,NULL,NULL,NULL,NULL,NULL),
    (4,1,'sergey-levin','ravil-sayfutdinov',1,41,'sergey-levin','6/3 6/0'),
    (4,2,'nurbek-nurbekov','shavkat-mihmanov',5,4,'nurbek-nurbekov','6/3 6/4'),
    (4,3,'amir-kanaev','altynbek-zhanybekov',3,43,'altynbek-zhanybekov','6/2 6/2'),
    (4,4,'elnur-omurzakov','azat-kubanychbek-uulu',55,50,'elnur-omurzakov','6/3 6/3'),
    (4,5,'dmitriy-pak','ahmedzhan-adzhuev',48,8,'ahmedzhan-adzhuev','2/6 6/2 11/9'),
    (4,6,'bakyt-kapakov','iskender-kadyrov',44,52,'iskender-kadyrov','6/4 6/4'),
    (4,7,'azatbek-musaev','salih-ismailov',46,38,'salih-ismailov','6/2 6/4'),
    (4,8,'bahram-mambetov','azat-bazarkulov',7,2,'bahram-mambetov','6/3 7/6(7-5)'),
    (4,9,'bekzhan-kylychbekov','imar-kamalov',32,9,'bekzhan-kylychbekov','6/3 3/6 10/8'),
    (4,10,'eren-kamchibekov','zhakshylyk-aytbaev',53,29,'zhakshylyk-aytbaev','6/1 7/6(7-0)'),
    (4,11,'nur-tulebaev','murat-alaychyev',14,6,'murat-alaychyev','6/4 6/4'),
    (4,12,'salman-beyshenaliev','ulan-tagaybek-uulu',23,34,'salman-beyshenaliev','6/0 6/3'),
    (4,13,'alier-mahmuthodzhaev','nursultan-zhunusov',16,25,'alier-mahmuthodzhaev','W/O'),
    (4,14,'timur-uzagaliev','atay-begaliev',37,45,'atay-begaliev','6/1 6/1'),
    (4,15,'beksultan-rustamov','erbol-abdyakimov',35,54,'beksultan-rustamov','W/O'),
    (4,16,'nursultan-ulukbekov','nurmat-sakebaev',39,18,NULL,NULL),
    (4,17,'sultan-ibragimov','aleksandr-kim',33,24,'sultan-ibragimov','W/O'),
    (4,18,'allayar-nasyrov','omurbek-zholdoshev',28,36,'allayar-nasyrov','6/4 6/1'),
    (4,19,'suvar-ayylchiev','musa-zhanybekov',19,27,'suvar-ayylchiev','W/O'),
    (4,20,'aydar-orozbaev','adlet-mamyrov',42,47,'adlet-mamyrov','6/2 6/0'),
    (4,21,'altynbek-zhoogachiev','rustam-ushur',49,40,NULL,NULL),
    (4,22,'sanzhar-ergeshaliev','vladimir-antonenko',21,20,'sanzhar-ergeshaliev','W/O'),
    (4,23,NULL,'aydin-daniyarov',NULL,11,'aydin-daniyarov','BYE'),
    (4,24,NULL,'adil-valimamedov',NULL,10,'adil-valimamedov','BYE'),
    (4,25,'timofey-kim',NULL,17,NULL,'timofey-kim','BYE'),
    (4,26,'sultan-ayylchiev','askar-abaskanov',12,13,NULL,NULL),
    (4,27,NULL,NULL,NULL,NULL,NULL,NULL),
    (4,28,'atay-isaev',NULL,26,NULL,'atay-isaev','BYE'),
    (4,29,NULL,NULL,NULL,NULL,NULL,NULL),
    (4,30,NULL,NULL,NULL,NULL,NULL,NULL),
    (4,31,NULL,NULL,NULL,NULL,NULL,NULL),
    (4,32,NULL,NULL,NULL,NULL,NULL,NULL),
    (5,1,'sergey-levin','nurbek-nurbekov',1,5,'nurbek-nurbekov','W/O'),
    (5,2,'altynbek-zhanybekov','elnur-omurzakov',43,55,'altynbek-zhanybekov','6/3 6/2'),
    (5,3,'ravil-sayfutdinov','shavkat-mihmanov',41,4,'shavkat-mihmanov','W/O'),
    (5,4,'amir-kanaev','azat-kubanychbek-uulu',3,50,'azat-kubanychbek-uulu','W/O'),
    (5,5,'ahmedzhan-adzhuev','iskender-kadyrov',8,52,NULL,NULL),
    (5,6,'salih-ismailov','bahram-mambetov',38,7,'salih-ismailov','6/2 7/6'),
    (5,7,'dmitriy-pak','bakyt-kapakov',48,44,NULL,NULL),
    (5,8,'azatbek-musaev','azat-bazarkulov',46,2,NULL,NULL),
    (5,9,'bekzhan-kylychbekov','zhakshylyk-aytbaev',32,29,NULL,NULL),
    (5,10,'murat-alaychyev','salman-beyshenaliev',6,23,'salman-beyshenaliev','W/O'),
    (5,11,'imar-kamalov','eren-kamchibekov',9,53,NULL,NULL),
    (5,12,'nur-tulebaev','ulan-tagaybek-uulu',14,34,NULL,NULL),
    (5,13,'alier-mahmuthodzhaev','atay-begaliev',16,45,'atay-begaliev','6/1 6/3'),
    (5,14,'beksultan-rustamov',NULL,35,NULL,NULL,NULL),
    (5,15,'nursultan-zhunusov','timur-uzagaliev',25,37,'timur-uzagaliev','6/4 6/4'),
    (5,16,'erbol-abdyakimov',NULL,54,NULL,NULL,NULL),
    (5,17,'sultan-ibragimov','allayar-nasyrov',33,28,NULL,NULL),
    (5,18,'suvar-ayylchiev','adlet-mamyrov',19,47,NULL,NULL),
    (5,19,'aleksandr-kim','omurbek-zholdoshev',24,36,NULL,NULL),
    (5,20,'musa-zhanybekov','aydar-orozbaev',27,42,NULL,NULL),
    (5,21,NULL,'sanzhar-ergeshaliev',NULL,21,NULL,NULL),
    (5,22,'aydin-daniyarov','adil-valimamedov',11,10,'aydin-daniyarov','6/4 7/5'),
    (5,23,NULL,'vladimir-antonenko',NULL,20,NULL,NULL),
    (5,24,NULL,NULL,NULL,NULL,NULL,NULL),
    (5,25,'timofey-kim',NULL,17,NULL,NULL,NULL),
    (5,26,NULL,'atay-isaev',NULL,26,NULL,NULL),
    (5,27,NULL,NULL,NULL,NULL,NULL,NULL),
    (5,28,NULL,NULL,NULL,NULL,NULL,NULL),
    (5,29,NULL,NULL,NULL,NULL,NULL,NULL),
    (5,30,NULL,NULL,NULL,NULL,NULL,NULL),
    (5,31,NULL,NULL,NULL,NULL,NULL,NULL),
    (5,32,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,1,'nurbek-nurbekov','altynbek-zhanybekov',5,43,'altynbek-zhanybekov','6/0 6/4'),
    (6,2,'sergey-levin','elnur-omurzakov',1,55,'elnur-omurzakov','W/O'),
    (6,3,'shavkat-mihmanov','azat-kubanychbek-uulu',4,50,'azat-kubanychbek-uulu','6/3 4/6 6/2'),
    (6,4,'ravil-sayfutdinov','amir-kanaev',41,3,NULL,NULL),
    (6,5,NULL,'salih-ismailov',NULL,38,NULL,NULL),
    (6,6,NULL,'bahram-mambetov',NULL,7,NULL,NULL),
    (6,7,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,8,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,9,NULL,'salman-beyshenaliev',NULL,23,NULL,NULL),
    (6,10,NULL,'murat-alaychyev',NULL,6,NULL,NULL),
    (6,11,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,12,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,13,'atay-begaliev',NULL,45,NULL,NULL,NULL),
    (6,14,'alier-mahmuthodzhaev',NULL,16,NULL,NULL,NULL),
    (6,15,'timur-uzagaliev',NULL,37,NULL,NULL,NULL),
    (6,16,'nursultan-zhunusov',NULL,25,NULL,NULL,NULL),
    (6,17,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,18,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,19,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,20,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,21,NULL,'aydin-daniyarov',NULL,11,NULL,NULL),
    (6,22,NULL,'adil-valimamedov',NULL,10,NULL,NULL),
    (6,23,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,24,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,25,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,26,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,27,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,28,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,29,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,30,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,31,NULL,NULL,NULL,NULL,NULL,NULL),
    (6,32,NULL,NULL,NULL,NULL,NULL,NULL)
       ) AS s(rnd, ord_, p1, p2, s1, s2, winner, score)
 WHERE m.tournament_id = 'tbsh-futures-2026'
   AND m.round_number = s.rnd AND m.match_order = s.ord_;

ALTER TABLE public.matches ENABLE TRIGGER trg_advance_bracket;

-- Что получилось
SELECT round_number,
       count(*) AS cells,
       count(*) FILTER (WHERE score IS NOT NULL AND score <> 'BYE') AS played,
       count(*) FILTER (WHERE score = 'BYE') AS byes
  FROM matches WHERE tournament_id = 'tbsh-futures-2026'
 GROUP BY round_number ORDER BY round_number;
