-- ========================================
-- Test data: 5 courts + 5 coaches for services overview
-- Run in Supabase SQL Editor
-- ========================================

-- COURTS (5 test entries)
INSERT INTO courts (id, name, name_en, photo, street, street_en, building, district, district_en, city, city_en, court_types, partner, amenities, description, description_en)
VALUES
(
  'grand-slam-bishkek',
  'Grand Slam Bishkek',
  'Grand Slam Bishkek',
  'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800&q=80',
  'ул. Абдрахманова',
  'Abdrakhmanova St.',
  '150',
  'Первомайский',
  'Pervomaysky',
  'Бишкек',
  'Bishkek',
  '[{"type":"outdoor","surface":"hard","count":4,"price":"1500","partner":false},{"type":"indoor","surface":"carpet","count":2,"price":"2500","partner":false}]',
  false,
  '{"parking","shower","wifi","cafe"}',
  'Современный теннисный центр с 6 кортами.',
  'Modern tennis center with 6 courts.'
),
(
  'ala-archa-tennis',
  'Ала-Арча Теннис',
  'Ala-Archa Tennis',
  'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800&q=80',
  'ул. Горького',
  'Gorky St.',
  '75',
  'Ленинский',
  'Leninsky',
  'Бишкек',
  'Bishkek',
  '[{"type":"outdoor","surface":"clay","count":3,"price":"1200","partner":false},{"type":"outdoor","surface":"hard","count":2,"price":"1000","partner":false}]',
  false,
  '{"parking","shower"}',
  'Открытые грунтовые и хардовые корты.',
  'Outdoor clay and hard courts.'
),
(
  'dordoy-sport',
  'Дордой Спорт',
  'Dordoy Sport',
  'https://images.unsplash.com/photo-1530915534664-4ac6423816b7?w=800&q=80',
  'ул. Жибек Жолу',
  'Jibek Jolu St.',
  '380',
  'Свердловский',
  'Sverdlovsky',
  'Бишкек',
  'Bishkek',
  '[{"type":"indoor","surface":"hard","count":3,"price":"2000","partner":false}]',
  false,
  '{"parking","shower","wifi","shop"}',
  'Крытый теннисный комплекс.',
  'Indoor tennis complex.'
),
(
  'bishkek-park-tennis',
  'Бишкек Парк Теннис',
  'Bishkek Park Tennis',
  'https://images.unsplash.com/photo-1542144582-1ba00456b5e3?w=800&q=80',
  'бул. Эркиндик',
  'Erkindik Blvd.',
  '25',
  'Октябрьский',
  'Oktyabrsky',
  'Бишкек',
  'Bishkek',
  '[{"type":"outdoor","surface":"hard","count":2,"price":"800","partner":false},{"type":"outdoor","surface":"clay","count":1,"price":"900","partner":false}]',
  true,
  '{"parking","cafe"}',
  'Корты в центре города рядом с парком.',
  'Courts in city center near the park.'
),
(
  'champion-arena',
  'Champion Arena',
  'Champion Arena',
  'https://images.unsplash.com/photo-1560012057-4372e14c5085?w=800&q=80',
  'ул. Ахунбаева',
  'Akhunbaeva St.',
  '200',
  'Первомайский',
  'Pervomaysky',
  'Бишкек',
  'Bishkek',
  '[{"type":"indoor","surface":"hard","count":4,"price":"1800","partner":false},{"type":"indoor","surface":"carpet","count":2,"price":"2200","partner":false}]',
  false,
  '{"parking","shower","wifi","cafe","shop"}',
  'Премиальный теннисный клуб.',
  'Premium tennis club.'
)
ON CONFLICT (id) DO NOTHING;

-- COACHES (5 test entries)
INSERT INTO coaches (id, last_name, first_name, last_name_en, first_name_en, name, name_en, photo, position, position_en, tags, experience, price, court, court_en, phone, short_desc, short_desc_en)
VALUES
(
  'smirnov-aleksey',
  'Смирнов',
  'Алексей',
  'Smirnov',
  'Aleksey',
  'Смирнов Алексей',
  'Aleksey Smirnov',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
  'Старший тренер',
  'Senior Coach',
  '{"adults","individual","advanced"}',
  15,
  3000,
  'Grand Slam Bishkek',
  'Grand Slam Bishkek',
  '+996555100100',
  'Мастер спорта, 15 лет опыта.',
  'Master of sports, 15 years experience.'
),
(
  'kim-anna',
  'Ким',
  'Анна',
  'Kim',
  'Anna',
  'Ким Анна',
  'Anna Kim',
  'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80',
  'Тренер',
  'Coach',
  '{"adults","kids","group","beginner"}',
  8,
  2000,
  'Ала-Арча Теннис',
  'Ala-Archa Tennis',
  '+996555200200',
  'Специализация на детском теннисе.',
  'Specializes in kids tennis.'
),
(
  'orozov-timur',
  'Орозов',
  'Тимур',
  'Orozov',
  'Timur',
  'Орозов Тимур',
  'Timur Orozov',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80',
  'Тренер по подготовке',
  'Fitness Coach',
  '{"adults","individual","group","advanced","beginner"}',
  12,
  2500,
  'Дордой Спорт',
  'Dordoy Sport',
  '+996555300300',
  'Физическая подготовка и техника.',
  'Physical training and technique.'
),
(
  'ivanova-maria',
  'Иванова',
  'Мария',
  'Ivanova',
  'Maria',
  'Иванова Мария',
  'Maria Ivanova',
  'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80',
  'Детский тренер',
  'Kids Coach',
  '{"kids","group","beginner"}',
  5,
  1500,
  'Бишкек Парк Теннис',
  'Bishkek Park Tennis',
  '+996555400400',
  'Работа с детьми от 5 лет.',
  'Working with children from age 5.'
),
(
  'volkov-dmitriy',
  'Волков',
  'Дмитрий',
  'Volkov',
  'Dmitriy',
  'Волков Дмитрий',
  'Dmitriy Volkov',
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80',
  'Тренер про-уровня',
  'Pro-Level Coach',
  '{"adults","individual","advanced"}',
  20,
  4000,
  'Champion Arena',
  'Champion Arena',
  '+996555500500',
  'Бывший профессиональный игрок.',
  'Former professional player.'
)
ON CONFLICT (id) DO NOTHING;
